-- Catálogo global necesario en instalaciones creadas sólo con migraciones.
-- Snapshot del catálogo comercial vigente: 11 categorías y 48 subcategorías.
-- Aditiva: conserva IDs, cambios, inactivos y referencias existentes. No crea productos ni tenants.
INSERT INTO "ProductoCategoriaComercial" ("id", "codigo", "nombre", "descripcion", "orden", "activo", "updatedAt")
SELECT gen_random_uuid(), x.codigo, x.nombre, x.descripcion, x.orden, true, CURRENT_TIMESTAMP
FROM jsonb_to_recordset($catalogo$[
{"codigo":"impresion_hoja","nombre":"Impresión comercial en hoja","descripcion":"Productos impresos sobre papel, cartulina o adhesivo en hoja.","orden":1},
{"codigo":"editorial_encuadernacion","nombre":"Editorial, formularios y encuadernación","descripcion":"Productos editoriales, talonarios, blocks y piezas encuadernadas.","orden":2},
{"codigo":"gran_formato_flexible","nombre":"Gran formato flexible","descripcion":"Vinilos, lonas, banners, displays y soportes flexibles por área.","orden":3},
{"codigo":"senalectica_rigidos","nombre":"Señalética, rígidos y corpóreos","descripcion":"Rígidos impresos, placas, carteles y letras corpóreas.","orden":4},
{"codigo":"packaging_pop","nombre":"Packaging, troquelado y POP","descripcion":"Packaging, etiquetas, troquelados y exhibidores POP.","orden":5},
{"codigo":"textil_personalizacion","nombre":"Textil y personalización","descripcion":"Indumentaria, transfer, objetos personalizados y merchandising.","orden":6},
{"codigo":"grabado_corte_decorativo","nombre":"Grabado, corte y decoración especial","descripcion":"Grabado láser, corte láser/CNC y acabados decorativos especiales.","orden":7},
{"codigo":"terminaciones_postproduccion","nombre":"Terminaciones y postproducción","descripcion":"Laminados, barnices, plegados, perforados y modificaciones.","orden":8},
{"codigo":"carteleria_montaje","nombre":"Cartelería estructural, luminosos e instalación","descripcion":"Estructuras, luminosos, montaje e instalación en sitio.","orden":9},
{"codigo":"servicios_logistica","nombre":"Servicios profesionales, logística y custom","descripcion":"Diseño, pruebas, toma de medidas, envío y productos a medida.","orden":10},
{"codigo":"sellos","nombre":"Sellos","descripcion":"Sellos automáticos y manuales fabricados con goma grabada a láser.","orden":11}
]$catalogo$::jsonb)
AS x(codigo text, nombre text, descripcion text, orden integer)
ON CONFLICT ("codigo") DO NOTHING;

INSERT INTO "ProductoSubcategoriaComercial" ("id", "categoriaId", "codigo", "nombre", "descripcion", "atributosSchemaJson", "orden", "activo", "updatedAt")
SELECT gen_random_uuid(), categoria.id, x.codigo, x.nombre, x.descripcion, x."atributosSchemaJson", x.orden, true, CURRENT_TIMESTAMP
FROM jsonb_to_recordset($catalogo$[
{"categoriaCodigo":"impresion_hoja","codigo":"tarjetas","nombre":"Tarjetas","descripcion":"Tarjetas personales, comerciales y piezas chicas en hoja.","atributosSchemaJson":[{"key":"medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"caras","label":"Caras","tipo":"text","visible":true,"orden":30},{"key":"impresion","label":"Impresión/Color","tipo":"text","visible":true,"orden":40}],"orden":1},
{"categoriaCodigo":"impresion_hoja","codigo":"volantes_folletos","nombre":"Volantes y folletos","descripcion":"Volantes, flyers, dípticos y trípticos impresos en hoja.","atributosSchemaJson":[{"key":"medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"caras","label":"Caras","tipo":"text","visible":true,"orden":30},{"key":"impresion","label":"Impresión/Color","tipo":"text","visible":true,"orden":40}],"orden":2},
{"categoriaCodigo":"impresion_hoja","codigo":"papeleria_comercial","nombre":"Papelería comercial","descripcion":"Membretes, sobres, carpetas simples y papelería institucional.","atributosSchemaJson":[{"key":"medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"caras","label":"Caras","tipo":"text","visible":true,"orden":30},{"key":"impresion","label":"Impresión/Color","tipo":"text","visible":true,"orden":40}],"orden":3},
{"categoriaCodigo":"impresion_hoja","codigo":"stickers_hoja","nombre":"Stickers en hoja","descripcion":"Stickers y calcomanías impresas en hoja.","atributosSchemaJson":[{"key":"medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"caras","label":"Caras","tipo":"text","visible":true,"orden":30},{"key":"impresion","label":"Impresión/Color","tipo":"text","visible":true,"orden":40}],"orden":4},
{"categoriaCodigo":"impresion_hoja","codigo":"postales_invitaciones","nombre":"Postales e invitaciones","descripcion":"Piezas sociales, invitaciones, postales y tarjetas especiales.","atributosSchemaJson":[{"key":"medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"caras","label":"Caras","tipo":"text","visible":true,"orden":30},{"key":"impresion","label":"Impresión/Color","tipo":"text","visible":true,"orden":40}],"orden":5},
{"categoriaCodigo":"editorial_encuadernacion","codigo":"talonarios","nombre":"Talonarios","descripcion":"Talonarios numerados, duplicados y triplicados.","atributosSchemaJson":[{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":10},{"key":"tipo_copia","label":"Tipo de copia","tipo":"text","visible":true,"orden":20},{"key":"hojas_por_talonario","label":"Hojas por talonario/block","tipo":"text","visible":true,"orden":30},{"key":"numeracion","label":"Numeración","tipo":"text","visible":true,"orden":40},{"key":"encuadernacion_base","label":"Encuadernación base","tipo":"text","visible":true,"orden":50}],"orden":1},
{"categoriaCodigo":"editorial_encuadernacion","codigo":"blocks_formularios","nombre":"Blocks y formularios","descripcion":"Blocks, formularios, remitos y piezas autocopiativas.","atributosSchemaJson":[{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":10},{"key":"tipo_copia","label":"Tipo de copia","tipo":"text","visible":true,"orden":20},{"key":"hojas_por_talonario","label":"Hojas por talonario/block","tipo":"text","visible":true,"orden":30},{"key":"numeracion","label":"Numeración","tipo":"text","visible":true,"orden":40},{"key":"encuadernacion_base","label":"Encuadernación base","tipo":"text","visible":true,"orden":50}],"orden":2},
{"categoriaCodigo":"editorial_encuadernacion","codigo":"revistas_cuadernillos","nombre":"Revistas y cuadernillos","descripcion":"Revistas, catálogos, cuadernillos y publicaciones simples.","atributosSchemaJson":[{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":10},{"key":"tipo_copia","label":"Tipo de copia","tipo":"text","visible":true,"orden":20},{"key":"hojas_por_talonario","label":"Hojas por talonario/block","tipo":"text","visible":true,"orden":30},{"key":"numeracion","label":"Numeración","tipo":"text","visible":true,"orden":40},{"key":"encuadernacion_base","label":"Encuadernación base","tipo":"text","visible":true,"orden":50}],"orden":3},
{"categoriaCodigo":"editorial_encuadernacion","codigo":"anillados_wire_o","nombre":"Anillados y wire-o","descripcion":"Anillados plásticos, wire-o y encuadernaciones con espiral.","atributosSchemaJson":[{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":10},{"key":"tipo_copia","label":"Tipo de copia","tipo":"text","visible":true,"orden":20},{"key":"hojas_por_talonario","label":"Hojas por talonario/block","tipo":"text","visible":true,"orden":30},{"key":"numeracion","label":"Numeración","tipo":"text","visible":true,"orden":40},{"key":"encuadernacion_base","label":"Encuadernación base","tipo":"text","visible":true,"orden":50}],"orden":4},
{"categoriaCodigo":"editorial_encuadernacion","codigo":"engrapados","nombre":"Engrapados","descripcion":"Cuadernillos, revistas y piezas engrapadas.","atributosSchemaJson":[{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":10},{"key":"tipo_copia","label":"Tipo de copia","tipo":"text","visible":true,"orden":20},{"key":"hojas_por_talonario","label":"Hojas por talonario/block","tipo":"text","visible":true,"orden":30},{"key":"numeracion","label":"Numeración","tipo":"text","visible":true,"orden":40},{"key":"encuadernacion_base","label":"Encuadernación base","tipo":"text","visible":true,"orden":50}],"orden":5},
{"categoriaCodigo":"gran_formato_flexible","codigo":"vinilos_impresos","nombre":"Vinilos impresos","descripcion":"Vinilo adhesivo impreso, laminado o instalado.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnologia","label":"Tecnología","tipo":"text","visible":true,"orden":30}],"orden":1},
{"categoriaCodigo":"gran_formato_flexible","codigo":"vinilos_corte","nombre":"Vinilos de corte","descripcion":"Vinilo de corte, letras adhesivas y calcos sin impresión full color.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnologia","label":"Tecnología","tipo":"text","visible":true,"orden":30}],"orden":2},
{"categoriaCodigo":"gran_formato_flexible","codigo":"lonas_banners","nombre":"Lonas y banners","descripcion":"Lonas impresas, banners, front, back y blockout.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnologia","label":"Tecnología","tipo":"text","visible":true,"orden":30}],"orden":3},
{"categoriaCodigo":"gran_formato_flexible","codigo":"mesh_microperforado","nombre":"Mesh y microperforado","descripcion":"Materiales perforados o mesh para vidrieras, fachadas y exterior.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnologia","label":"Tecnología","tipo":"text","visible":true,"orden":30}],"orden":4},
{"categoriaCodigo":"gran_formato_flexible","codigo":"rollups_displays","nombre":"Roll-ups y displays","descripcion":"Roll-ups, portabanners y displays transportables.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnologia","label":"Tecnología","tipo":"text","visible":true,"orden":30}],"orden":5},
{"categoriaCodigo":"senalectica_rigidos","codigo":"rigidos_impresos","nombre":"Rígidos impresos","descripcion":"PVC, MDF, acrílico, foam y rígidos impresos o intervenidos.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":1},
{"categoriaCodigo":"senalectica_rigidos","codigo":"senaletica_placas","nombre":"Señalética y placas","descripcion":"Placas, señalética interior/exterior y nomencladores.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":2},
{"categoriaCodigo":"senalectica_rigidos","codigo":"letras_corporeas","nombre":"Letras corpóreas","descripcion":"Letras corpóreas en MDF, acrílico, PVC, metal o similares.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":3},
{"categoriaCodigo":"senalectica_rigidos","codigo":"cuadros_decorativos","nombre":"Cuadros decorativos","descripcion":"Cuadros, bastidores, placas decorativas y piezas de interior.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":4},
{"categoriaCodigo":"senalectica_rigidos","codigo":"carteles_con_forma","nombre":"Carteles con forma","descripcion":"Carteles rígidos cortados con forma, router o láser.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":5},
{"categoriaCodigo":"packaging_pop","codigo":"cajas_packaging","nombre":"Cajas y packaging","descripcion":"Cajas, estuches, fajas y piezas de packaging.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":30},{"key":"sistema_estructural","label":"Sistema estructural","tipo":"text","visible":true,"orden":40}],"orden":1},
{"categoriaCodigo":"packaging_pop","codigo":"troquelados_digitales","nombre":"Troquelados digitales","descripcion":"Piezas con corte digital, formas especiales y prototipos.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":30},{"key":"sistema_estructural","label":"Sistema estructural","tipo":"text","visible":true,"orden":40}],"orden":2},
{"categoriaCodigo":"packaging_pop","codigo":"exhibidores_pop","nombre":"Exhibidores POP","descripcion":"Exhibidores, displays, piezas de punto de venta y material POP.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":30},{"key":"sistema_estructural","label":"Sistema estructural","tipo":"text","visible":true,"orden":40}],"orden":3},
{"categoriaCodigo":"packaging_pop","codigo":"etiquetas_packaging","nombre":"Etiquetas de packaging","descripcion":"Etiquetas, fajas, stickers y aplicaciones para packaging.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":30},{"key":"sistema_estructural","label":"Sistema estructural","tipo":"text","visible":true,"orden":40}],"orden":4},
{"categoriaCodigo":"textil_personalizacion","codigo":"remeras_indumentaria","nombre":"Remeras e indumentaria","descripcion":"Prendas impresas, estampadas o personalizadas.","atributosSchemaJson":[{"key":"prenda_base","label":"Prenda/Base","tipo":"text","visible":true,"orden":10},{"key":"tecnica","label":"Técnica","tipo":"text","visible":true,"orden":20},{"key":"ubicacion","label":"Ubicación","tipo":"text","visible":true,"orden":30},{"key":"color_talle","label":"Color/Talle","tipo":"text","visible":true,"orden":40}],"orden":1},
{"categoriaCodigo":"textil_personalizacion","codigo":"dtf_transfer","nombre":"DTF y transfer","descripcion":"Transfers DTF, DTG, sublimación y aplicaciones térmicas.","atributosSchemaJson":[{"key":"prenda_base","label":"Prenda/Base","tipo":"text","visible":true,"orden":10},{"key":"tecnica","label":"Técnica","tipo":"text","visible":true,"orden":20},{"key":"ubicacion","label":"Ubicación","tipo":"text","visible":true,"orden":30},{"key":"color_talle","label":"Color/Talle","tipo":"text","visible":true,"orden":40}],"orden":2},
{"categoriaCodigo":"textil_personalizacion","codigo":"objetos_personalizados","nombre":"Objetos personalizados","descripcion":"Tazas, llaveros, placas, regalos y objetos intervenidos.","atributosSchemaJson":[{"key":"objeto_base","label":"Objeto/Base","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnica","label":"Técnica","tipo":"text","visible":true,"orden":30},{"key":"area_aplicacion","label":"Área de aplicación","tipo":"text","visible":true,"orden":40}],"orden":3},
{"categoriaCodigo":"textil_personalizacion","codigo":"merchandising","nombre":"Merchandising","descripcion":"Merchandising promocional y productos seriados personalizados.","atributosSchemaJson":[{"key":"objeto_base","label":"Objeto/Base","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"tecnica","label":"Técnica","tipo":"text","visible":true,"orden":30},{"key":"area_aplicacion","label":"Área de aplicación","tipo":"text","visible":true,"orden":40}],"orden":4},
{"categoriaCodigo":"grabado_corte_decorativo","codigo":"grabado_laser","nombre":"Grabado láser","descripcion":"Grabado superficial sobre acrílico, madera, metal, cuero u objetos.","atributosSchemaJson":[{"key":"servicio_proceso","label":"Servicio/Proceso","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":30},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":40}],"orden":1},
{"categoriaCodigo":"grabado_corte_decorativo","codigo":"corte_laser","nombre":"Corte láser","descripcion":"Corte láser de placas, piezas y formas complejas.","atributosSchemaJson":[{"key":"servicio_proceso","label":"Servicio/Proceso","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":30},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":40}],"orden":2},
{"categoriaCodigo":"grabado_corte_decorativo","codigo":"corte_cnc","nombre":"Corte CNC","descripcion":"Router CNC, cortes, fresados y piezas rígidas mecanizadas.","atributosSchemaJson":[{"key":"servicio_proceso","label":"Servicio/Proceso","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":30},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":40}],"orden":3},
{"categoriaCodigo":"grabado_corte_decorativo","codigo":"hotstamping_dorado_gofrado","nombre":"Hotstamping, dorado y gofrado","descripcion":"Acabados decorativos con foil, relieve, gofrado o matrices.","atributosSchemaJson":[{"key":"servicio_proceso","label":"Servicio/Proceso","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Medidas/Formato","tipo":"text","visible":true,"orden":30},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":40}],"orden":4},
{"categoriaCodigo":"terminaciones_postproduccion","codigo":"laminados_plastificados","nombre":"Laminados y plastificados","descripcion":"Laminados, plastificados y films protectores.","atributosSchemaJson":[{"key":"servicio_vendido","label":"Servicio vendido","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":30},{"key":"detalle_tecnico","label":"Detalle técnico","tipo":"text","visible":true,"orden":40}],"orden":1},
{"categoriaCodigo":"terminaciones_postproduccion","codigo":"barnices","nombre":"Barnices","descripcion":"Barnices UV, al agua, sectorizados o protectores.","atributosSchemaJson":[{"key":"servicio_vendido","label":"Servicio vendido","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":30},{"key":"detalle_tecnico","label":"Detalle técnico","tipo":"text","visible":true,"orden":40}],"orden":2},
{"categoriaCodigo":"terminaciones_postproduccion","codigo":"plegados","nombre":"Plegados","descripcion":"Plegados simples, dípticos, trípticos, acordeón y similares.","atributosSchemaJson":[{"key":"servicio_vendido","label":"Servicio vendido","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":30},{"key":"detalle_tecnico","label":"Detalle técnico","tipo":"text","visible":true,"orden":40}],"orden":3},
{"categoriaCodigo":"terminaciones_postproduccion","codigo":"perforados_puntillados","nombre":"Perforados y puntillados","descripcion":"Perforaciones, puntillados, troqueles simples y desprendibles.","atributosSchemaJson":[{"key":"servicio_vendido","label":"Servicio vendido","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":30},{"key":"detalle_tecnico","label":"Detalle técnico","tipo":"text","visible":true,"orden":40}],"orden":4},
{"categoriaCodigo":"terminaciones_postproduccion","codigo":"numerado_redondeado_modificaciones","nombre":"Numerado, redondeado y modificaciones","descripcion":"Numeración, redondeo de puntas y modificaciones manuales/postproducción.","atributosSchemaJson":[{"key":"servicio_vendido","label":"Servicio vendido","tipo":"text","visible":true,"orden":10},{"key":"material_base","label":"Material base","tipo":"text","visible":true,"orden":20},{"key":"formato_medidas","label":"Formato/Medidas","tipo":"text","visible":true,"orden":30},{"key":"detalle_tecnico","label":"Detalle técnico","tipo":"text","visible":true,"orden":40}],"orden":5},
{"categoriaCodigo":"carteleria_montaje","codigo":"estructuras_metalicas","nombre":"Estructuras metálicas","descripcion":"Estructuras, marcos, bastidores y herrería para cartelería.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":1},
{"categoriaCodigo":"carteleria_montaje","codigo":"luminosos_led","nombre":"Luminosos y LED","descripcion":"Carteles luminosos, letras iluminadas, módulos LED y fuentes.","atributosSchemaJson":[{"key":"medidas","label":"Medidas","tipo":"text","visible":true,"orden":10},{"key":"material","label":"Material","tipo":"text","visible":true,"orden":20},{"key":"espesor","label":"Espesor","tipo":"text","visible":true,"orden":30},{"key":"tecnologia","label":"Tecnología/Proceso","tipo":"text","visible":true,"orden":40},{"key":"tipo_pieza","label":"Tipo de pieza","tipo":"text","visible":true,"orden":50}],"orden":2},
{"categoriaCodigo":"carteleria_montaje","codigo":"montaje_carteleria","nombre":"Montaje de cartelería","descripcion":"Montaje físico, armado estructural y fijaciones de cartelería.","atributosSchemaJson":[{"key":"zona","label":"Zona","tipo":"text","visible":true,"orden":10},{"key":"superficie","label":"Superficie","tipo":"text","visible":true,"orden":20},{"key":"altura_dificultad","label":"Altura/Dificultad","tipo":"text","visible":true,"orden":30},{"key":"m2_medidas_instaladas","label":"m² o medidas instaladas","tipo":"text","visible":true,"orden":40},{"key":"tipo_soporte_pieza","label":"Tipo de soporte/pieza","tipo":"text","visible":true,"orden":50}],"orden":3},
{"categoriaCodigo":"carteleria_montaje","codigo":"instalacion_en_sitio","nombre":"Instalación en sitio","descripcion":"Colocación, instalación y trabajo en domicilio del cliente.","atributosSchemaJson":[{"key":"zona","label":"Zona","tipo":"text","visible":true,"orden":10},{"key":"superficie","label":"Superficie","tipo":"text","visible":true,"orden":20},{"key":"altura_dificultad","label":"Altura/Dificultad","tipo":"text","visible":true,"orden":30},{"key":"m2_medidas_instaladas","label":"m² o medidas instaladas","tipo":"text","visible":true,"orden":40},{"key":"tipo_soporte_pieza","label":"Tipo de soporte/pieza","tipo":"text","visible":true,"orden":50}],"orden":4},
{"categoriaCodigo":"servicios_logistica","codigo":"diseno_grafico","nombre":"Diseño gráfico","descripcion":"Servicio de diseño, adaptación o preparación de arte.","atributosSchemaJson":[{"key":"tipo_servicio","label":"Tipo de servicio","tipo":"text","visible":true,"orden":10},{"key":"alcance","label":"Alcance","tipo":"text","visible":true,"orden":20},{"key":"horas_estimadas","label":"Horas estimadas","tipo":"text","visible":true,"orden":30},{"key":"entregable","label":"Entregable","tipo":"text","visible":true,"orden":40}],"orden":1},
{"categoriaCodigo":"servicios_logistica","codigo":"proof_muestras","nombre":"Proof y muestras","descripcion":"Pruebas de color, muestras físicas y prototipos de aprobación.","atributosSchemaJson":[{"key":"tipo_servicio","label":"Tipo de servicio","tipo":"text","visible":true,"orden":10},{"key":"alcance","label":"Alcance","tipo":"text","visible":true,"orden":20},{"key":"horas_estimadas","label":"Horas estimadas","tipo":"text","visible":true,"orden":30},{"key":"entregable","label":"Entregable","tipo":"text","visible":true,"orden":40}],"orden":2},
{"categoriaCodigo":"servicios_logistica","codigo":"toma_medidas","nombre":"Toma de medidas","descripcion":"Visitas para medición, relevamiento y evaluación técnica.","atributosSchemaJson":[{"key":"zona","label":"Zona","tipo":"text","visible":true,"orden":10},{"key":"superficie","label":"Superficie","tipo":"text","visible":true,"orden":20},{"key":"altura_dificultad","label":"Altura/Dificultad","tipo":"text","visible":true,"orden":30},{"key":"m2_medidas_instaladas","label":"m² o medidas instaladas","tipo":"text","visible":true,"orden":40},{"key":"tipo_soporte_pieza","label":"Tipo de soporte/pieza","tipo":"text","visible":true,"orden":50}],"orden":3},
{"categoriaCodigo":"servicios_logistica","codigo":"envio_despacho","nombre":"Envío y despacho","descripcion":"Envío, logística, flete, cadetería y despacho.","atributosSchemaJson":[{"key":"zona","label":"Zona","tipo":"text","visible":true,"orden":10},{"key":"superficie","label":"Superficie","tipo":"text","visible":true,"orden":20},{"key":"altura_dificultad","label":"Altura/Dificultad","tipo":"text","visible":true,"orden":30},{"key":"m2_medidas_instaladas","label":"m² o medidas instaladas","tipo":"text","visible":true,"orden":40},{"key":"tipo_soporte_pieza","label":"Tipo de soporte/pieza","tipo":"text","visible":true,"orden":50}],"orden":4},
{"categoriaCodigo":"servicios_logistica","codigo":"producto_a_medida","nombre":"Producto a medida","descripcion":"Producto custom o pendiente de clasificación comercial.","atributosSchemaJson":[{"key":"tipo_servicio","label":"Tipo de servicio","tipo":"text","visible":true,"orden":10},{"key":"alcance","label":"Alcance","tipo":"text","visible":true,"orden":20},{"key":"horas_estimadas","label":"Horas estimadas","tipo":"text","visible":true,"orden":30},{"key":"entregable","label":"Entregable","tipo":"text","visible":true,"orden":40}],"orden":5},
{"categoriaCodigo":"sellos","codigo":"sellos_automaticos","nombre":"Sellos automáticos","descripcion":"Sellos autoentintables (Trodat Printy, Professional, etc.) con goma grabada a láser.","atributosSchemaJson":[{"key":"modelo_sello","label":"Marca y modelo","tipo":"text","visible":true,"orden":10},{"key":"tamano_polimero","label":"Tamaño de polímero","tipo":"text","visible":true,"orden":20},{"key":"lineas_texto","label":"Líneas de texto","tipo":"text","visible":true,"orden":30},{"key":"color_tinta","label":"Color de tinta","tipo":"text","visible":true,"orden":40},{"key":"texto_grabado","label":"Texto a grabar","tipo":"text","visible":true,"orden":50}],"orden":1},
{"categoriaCodigo":"sellos","codigo":"sellos_manuales","nombre":"Sellos manuales","descripcion":"Sellos con mango de madera o plástico, usan almohadilla aparte.","atributosSchemaJson":[{"key":"modelo_sello","label":"Marca y modelo","tipo":"text","visible":true,"orden":10},{"key":"tamano_polimero","label":"Tamaño de polímero","tipo":"text","visible":true,"orden":20},{"key":"lineas_texto","label":"Líneas de texto","tipo":"text","visible":true,"orden":30},{"key":"color_tinta","label":"Color de tinta","tipo":"text","visible":true,"orden":40},{"key":"texto_grabado","label":"Texto a grabar","tipo":"text","visible":true,"orden":50}],"orden":2}
]$catalogo$::jsonb)
AS x("categoriaCodigo" text, codigo text, nombre text, descripcion text, "atributosSchemaJson" jsonb, orden integer)
JOIN "ProductoCategoriaComercial" categoria ON categoria.codigo = x."categoriaCodigo"
ON CONFLICT ("codigo") DO NOTHING;
