import type {
  FamiliaMateriaPrima,
  SubfamiliaMateriaPrima,
  UnidadMateriaPrima,
} from "@/lib/materias-primas";
import type { PlantillaMaquinaria } from "@/lib/maquinaria";
import {
  assertAnchoAntesDeAlto,
  assertCanonicalTemplateKeys,
} from "@/lib/canonical-keys";
import type { UnitCode } from "@/lib/unidades";

export type CampoTecnicoTemplate = {
  key: string;
  label: string;
  type: "text" | "number" | "boolean";
  unit?: UnitCode;
  /** Unidad de visualización preferida por defecto (puede diferir de `unit` que es la canónica). */
  preferredDisplayUnit?: UnitCode;
  options?: string[];
  required?: boolean;
  optional?: boolean;
};

export type MateriaPrimaTemplateDef = {
  id: string;
  nombre: string;
  descripcion: string;
  familia: FamiliaMateriaPrima;
  subfamilia: SubfamiliaMateriaPrima;
  tipoTecnico: string;
  unidadStock: UnidadMateriaPrima;
  unidadCompra: UnidadMateriaPrima;
  camposTecnicos: CampoTecnicoTemplate[];
  dimensionesVariante: string[];
  requiredAtributos: string[];
  atributosIniciales: Record<string, unknown>;
  /** Excepción puntual a la convención "sin unidad en la key": para declarar
   *  campos cuyos DATOS ya viven con key sufijada porque el motor los lee
   *  así (p.ej. `anchoMm`/`altoMm` de la hoja de chapa, que alimentan el
   *  nesting). Renombrarlos rompería el costeo; acá se blanquean. */
  allowUnitSuffixKeys?: string[];
  defaults?: {
    esConsumible?: boolean;
    esRepuesto?: boolean;
    esProductoBase?: boolean;
    lockEsConsumible?: boolean;
    lockEsRepuesto?: boolean;
    lockEsProductoBase?: boolean;
  };
};

export const SUSTRATO_HOJA_FORMATOS_PRESET = [
  { id: "a6_105x148", nombre: "A6", ancho: 10.5, alto: 14.8 },
  { id: "a5_148x210", nombre: "A5", ancho: 14.8, alto: 21.0 },
  { id: "a4_210x297", nombre: "A4", ancho: 21.0, alto: 29.7 },
  { id: "a3_297x420", nombre: "A3", ancho: 29.7, alto: 42.0 },
  { id: "sra3_325x475", nombre: "SRA3", ancho: 32.5, alto: 47.5 },
  { id: "sra3_plus_330x480", nombre: "SRA3+", ancho: 33.0, alto: 48.0 },
  { id: "sra3_plus_plus_325x500", nombre: "SRA3++", ancho: 32.5, alto: 50.0 },
  { id: "22x34_220x340", nombre: "22x34", ancho: 22.0, alto: 34.0 },
  { id: "carta_216x279", nombre: "Carta", ancho: 21.6, alto: 27.9 },
  { id: "oficio_216x356", nombre: "Oficio", ancho: 21.6, alto: 35.6 },
] as const;

const duplicatedSustratoHojaNames = SUSTRATO_HOJA_FORMATOS_PRESET.reduce<
  Record<string, number>
>((acc, item) => {
  acc[item.nombre] = (acc[item.nombre] ?? 0) + 1;
  return acc;
}, {});

const duplicatedSustratoHojaNameList = Object.entries(
  duplicatedSustratoHojaNames,
)
  .filter(([, count]) => count > 1)
  .map(([name]) => name);

if (duplicatedSustratoHojaNameList.length > 0) {
  throw new Error(
    `SUSTRATO_HOJA_FORMATOS_PRESET tiene nombres duplicados: ${duplicatedSustratoHojaNameList.join(", ")}`,
  );
}

const REPLACEMENT_COMPONENT_OPTIONS = [
  "fusor",
  "drum",
  "drum_opc",
  "developer",
  "developer_unit",
  "charge_unit",
  "drum_cleaning_blade",
  "correa_transferencia",
  "transfer_belt_itb",
  "transfer_roller",
  "fuser_belt",
  "pressure_roller",
  "fuser_cleaning_web",
  "wax_lubricant_bar",
  "fuser_stripper_finger",
  "waste_toner_subsystem",
  "cabezal",
  "lampara_uv",
  "fresa",
  "cuchilla",
  "filtro",
  "kit_mantenimiento",
  "otro",
] as const;

// 11 plantillas (2026-08: sin soldadora/cabina_pintura, + plancha_termica).
const MAQUINARIA_TEMPLATE_OPTIONS = [
  "impresora_laser",
  "duplicadora_digital",
  "impresora_gran_formato_por_area",
  "guillotina",
  "plotter_de_corte",
  "plotter_cad",
  "laminadora_bopp_rollo",
  "corte_laser",
  "router_cnc",
  "anilladora",
  "mesa_de_corte",
  "plancha_termica",
];

const REPLACEMENT_WEAR_UNIT_OPTIONS = [
  "copias_a4_equiv",
  "m2",
  "metros_lineales",
  "horas",
  "ciclos",
  "piezas",
];

export const REPLACEMENT_COMPONENT_LABELS: Record<string, string> = {
  fusor: "Fusor",
  drum: "Tambor (drum) genérico",
  drum_opc: "Tambor OPC",
  developer: "Revelador",
  developer_unit: "Unidad reveladora (developer unit)",
  charge_unit: "Unidad de carga (PCR/corona)",
  drum_cleaning_blade: "Cuchilla de limpieza de tambor",
  correa_transferencia: "Correa de transferencia",
  transfer_belt_itb: "Banda/correa de transferencia ITB",
  transfer_roller: "Rodillo de transferencia",
  fuser_belt: "Banda de fusor",
  pressure_roller: "Rodillo de presión",
  fuser_cleaning_web: "Web de limpieza del fusor",
  wax_lubricant_bar: "Barra de cera/lubricación",
  fuser_stripper_finger: "Uña separadora del fusor",
  waste_toner_subsystem: "Subsistema de residual de tóner",
  cabezal: "Cabezal",
  lampara_uv: "Lampara UV",
  fresa: "Fresa",
  cuchilla: "Cuchilla",
  filtro: "Filtro",
  kit_mantenimiento: "Kit de mantenimiento",
  otro: "Otro",
};

/**
 * Componentes de desgaste sugeridos por plantilla — v3.0 (2026-04-26).
 * Doc §5–§13: cada plantilla declara qué tipos de desgaste son comunes.
 */
const REPLACEMENT_COMPONENT_OPTIONS_BY_TEMPLATE: Record<
  PlantillaMaquinaria,
  string[]
> = {
  impresora_laser: [
    "fusor",
    "drum",
    "drum_opc",
    "developer",
    "developer_unit",
    "charge_unit",
    "drum_cleaning_blade",
    "correa_transferencia",
    "transfer_belt_itb",
    "transfer_roller",
    "fuser_belt",
    "pressure_roller",
    "fuser_cleaning_web",
    "wax_lubricant_bar",
    "fuser_stripper_finger",
    "waste_toner_subsystem",
    "filtro",
    "kit_mantenimiento",
    "otro",
  ],
  duplicadora_digital: ["otro"],
  // §6: gran formato unificado — cabezal + lámpara UV (si aplica) + filtro.
  impresora_gran_formato_por_area: [
    "cabezal",
    "lampara_uv",
    "correa_transferencia",
    "filtro",
    "kit_mantenimiento",
    "otro",
  ],
  router_cnc: ["fresa", "cuchilla", "filtro", "kit_mantenimiento", "otro"],
  corte_hilo_caliente: ["hilo", "kit_mantenimiento", "otro"],
  corte_laser: ["filtro", "cuchilla", "kit_mantenimiento", "otro"],
  guillotina: ["cuchilla", "kit_mantenimiento", "otro"],
  laminadora_bopp_rollo: ["cuchilla", "filtro", "kit_mantenimiento", "otro"],
  mesa_de_corte: ["cuchilla", "filtro", "kit_mantenimiento", "otro"],
  plotter_de_corte: ["cuchilla", "filtro", "kit_mantenimiento", "otro"],
  plotter_cad: ["cabezal", "filtro", "kit_mantenimiento", "otro"],
  anilladora: ["kit_mantenimiento", "otro"],
  plancha_termica: ["kit_mantenimiento", "otro"],
  // FDM: boquilla y cama. Resina: film FEP y pantalla LCD. Todos por horas de uso.
  impresora_3d: ["kit_mantenimiento", "otro"],
};

export const materiaPrimaTemplatesV1: MateriaPrimaTemplateDef[] = [
  {
    id: "sustrato_hoja_v1",
    nombre: "Sustrato hoja",
    descripcion: "Papel/cartulina en hoja o pliego para impresión",
    familia: "sustrato",
    subfamilia: "sustrato_hoja",
    tipoTecnico: "sustrato_hoja",
    unidadStock: "hoja",
    unidadCompra: "resma",
    camposTecnicos: [
      {
        key: "formatoComercial",
        label: "Nombre/Descripción",
        type: "text",
        required: true,
      },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "cm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "cm",
        required: true,
      },
      {
        key: "gramaje",
        label: "Gramaje",
        type: "number",
        unit: "g_m2",
        required: true,
      },
      { key: "material", label: "Material", type: "text", required: true },
      {
        key: "color",
        label: "Color",
        type: "text",
        options: ["Blanco", "Color"],
        required: false,
      },
      {
        key: "acabado",
        label: "Acabado",
        type: "text",
        options: ["Brillo", "Mate"],
        required: true,
      },
    ],
    dimensionesVariante: [
      "formatoComercial",
      "ancho",
      "alto",
      "gramaje",
      "material",
      "color",
      "acabado",
    ],
    requiredAtributos: [
      "formatoComercial",
      "ancho",
      "alto",
      "gramaje",
      "material",
      "acabado",
    ],
    atributosIniciales: {
      formatoComercial: "A4",
      ancho: 21,
      alto: 29.7,
      gramaje: 115,
      material: "ilustracion",
      color: "Blanco",
      acabado: "mate",
    },
  },
  {
    id: "sustrato_rollo_flexible_v1",
    nombre: "Sustrato rollo flexible",
    descripcion: "Vinilo/lona/film en rollo",
    familia: "sustrato",
    subfamilia: "sustrato_rollo_flexible",
    tipoTecnico: "sustrato_rollo_flexible",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho de rollo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "largo",
        label: "Largo de rollo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "acabado",
        label: "Acabado",
        type: "text",
        options: ["Brillante", "Mate"],
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo", "acabado"],
    requiredAtributos: ["ancho", "largo", "acabado"],
    atributosIniciales: {
      ancho: 1.27,
      largo: 50,
      acabado: "Brillante",
    },
  },
  {
    id: "vinilo_esmerilado_rollo_v1",
    nombre: "Vinilo esmerilado en rollo",
    descripcion: "Vinilo esmerilado blanco o gris en rollo",
    familia: "sustrato",
    subfamilia: "sustrato_rollo_flexible",
    tipoTecnico: "vinilo_esmerilado",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho de rollo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "largo",
        label: "Largo de rollo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "acabado",
        label: "Acabado",
        type: "text",
        options: ["Blanco", "Gris"],
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo", "acabado"],
    requiredAtributos: ["ancho", "largo", "acabado"],
    atributosIniciales: {
      ancho: 0.61,
      largo: 50,
      acabado: "Blanco",
    },
  },
  {
    id: "vinilo_de_corte_rollo_v1",
    nombre: "Vinilo de corte en rollo",
    descripcion: "Vinilo de corte de color en rollo para plotter de corte",
    familia: "sustrato",
    subfamilia: "vinilo_corte",
    tipoTecnico: "vinilo_de_corte_rollo",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho de rollo",
        type: "number",
        unit: "m",
        preferredDisplayUnit: "cm",
        required: true,
      },
      {
        key: "largo",
        label: "Largo de rollo",
        type: "number",
        unit: "m",
        required: true,
      },
      // El precio del vinilo de corte varía entre negro / blanco / color
      // (cualquier color): no hace falta la paleta completa. Los especiales
      // (holográfico, metalizado, reflectivo) quedan fuera en esta etapa.
      {
        key: "color",
        label: "Color",
        type: "text",
        options: ["Color", "Negro", "Blanco"],
        required: true,
      },
      {
        key: "acabado",
        label: "Acabado",
        type: "text",
        options: ["Brillo", "Mate"],
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo", "color", "acabado"],
    requiredAtributos: ["ancho", "largo", "color", "acabado"],
    atributosIniciales: {
      ancho: 0.61,
      largo: 50,
      color: "Blanco",
      acabado: "Brillo",
    },
  },
  {
    id: "sustrato_rigido_v1",
    nombre: "Sustrato rígido",
    descripcion: "PVC, acrílico, MDF, dibond y similares",
    familia: "sustrato",
    subfamilia: "sustrato_rigido",
    tipoTecnico: "sustrato_rigido",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "m",
        required: true,
      },
      { key: "alto", label: "Alto", type: "number", unit: "m", required: true },
      {
        key: "espesor",
        label: "Espesor",
        type: "number",
        unit: "mm",
        required: true,
      },
      { key: "colorBase", label: "Color base", type: "text", required: true },
    ],
    dimensionesVariante: ["ancho", "alto", "espesor", "colorBase"],
    requiredAtributos: ["ancho", "alto", "espesor", "colorBase"],
    atributosIniciales: {
      ancho: 1.22,
      alto: 2.44,
      espesor: 3,
      colorBase: "blanco",
    },
  },
  {
    id: "tinta_impresion_v1",
    nombre: "Tinta impresión",
    descripcion: "Tintas para solvente, UV, latex, DTF, sublimación",
    familia: "tinta_colorante",
    subfamilia: "tinta_impresion",
    tipoTecnico: "tinta_impresion",
    unidadStock: "ml",
    unidadCompra: "litro",
    camposTecnicos: [
      {
        key: "tecnologiaCompatible",
        label: "Tecnología compatible",
        type: "text",
        required: true,
      },
      { key: "color", label: "Color", type: "text", required: true },
      {
        key: "volumenPresentacion",
        label: "Volumen de presentación",
        type: "number",
        unit: "ml",
        required: true,
      },
      {
        key: "equipoCompatible",
        label: "Equipo compatible",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: ["color", "volumenPresentacion", "equipoCompatible"],
    requiredAtributos: ["tecnologiaCompatible", "color", "volumenPresentacion"],
    atributosIniciales: {
      tecnologiaCompatible: "impresora_gran_formato_por_area",
      color: "c",
      volumenPresentacion: 500,
      baseQuimica: "uv",
      rendimientoReferencia: 1,
    },
  },
  {
    id: "master_duplicadora_v1",
    nombre: "Máster para duplicadora",
    descripcion:
      "Rollo de máster térmico consumido una vez por original y cara.",
    familia: "tinta_colorante",
    subfamilia: "auxiliar_proceso",
    tipoTecnico: "master_duplicadora",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "largo",
        label: "Largo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "rendimientoMasters",
        label: "Másteres por rollo",
        type: "number",
        required: true,
      },
      {
        key: "equipoCompatible",
        label: "Equipo compatible",
        type: "text",
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo", "equipoCompatible"],
    requiredAtributos: [
      "ancho",
      "largo",
      "rendimientoMasters",
      "equipoCompatible",
    ],
    atributosIniciales: {
      ancho: 280,
      largo: 50,
      rendimientoMasters: 100,
      equipoCompatible: "Ricoh DX 2430",
    },
    defaults: {
      esConsumible: true,
      lockEsConsumible: true,
    },
  },
  {
    id: "toner_v1",
    nombre: "Tóner",
    descripcion: "Consumibles de impresión láser",
    familia: "tinta_colorante",
    subfamilia: "toner",
    tipoTecnico: "toner",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      { key: "color", label: "Color", type: "text", required: true },
      {
        key: "rendimientoPaginasIso",
        label: "Rendimiento",
        type: "number",
        required: true,
      },
      {
        key: "equipoCompatible",
        label: "Equipo compatible",
        type: "text",
        required: true,
      },
      {
        key: "presentacion",
        label: "Presentación",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: ["color", "rendimientoPaginasIso", "equipoCompatible"],
    requiredAtributos: ["color", "rendimientoPaginasIso", "equipoCompatible"],
    atributosIniciales: {
      color: "negro",
      rendimientoPaginasIso: 5000,
      oemOAlternativo: "oem",
      equipoCompatible: "generico",
    },
  },
  {
    id: "film_transferencia_v1",
    nombre: "Film transferencia",
    descripcion: "Film DTF PET o A/B UV",
    familia: "transferencia_laminacion",
    subfamilia: "film_transferencia",
    tipoTecnico: "film_transferencia",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "largo",
        label: "Largo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "tecnologiaCompatible",
        label: "Tecnología compatible",
        type: "text",
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo"],
    requiredAtributos: ["ancho", "largo", "tecnologiaCompatible"],
    atributosIniciales: {
      ancho: 600,
      largo: 100,
      tipoRelease: "cold_peel",
      espesorMicrones: 75,
      tecnologiaCompatible: "impresora_gran_formato_por_area",
    },
  },
  {
    id: "papel_transferencia_v1",
    nombre: "Papel transferencia",
    descripcion: "Papel de sublimación o transferencia",
    familia: "transferencia_laminacion",
    subfamilia: "papel_transferencia",
    tipoTecnico: "papel_transferencia",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "largo",
        label: "Largo",
        type: "number",
        unit: "m",
        optional: true,
      },
      {
        key: "gramaje",
        label: "Gramaje",
        type: "number",
        unit: "g_m2",
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "gramaje"],
    requiredAtributos: ["ancho", "gramaje"],
    atributosIniciales: {
      ancho: 610,
      largo: 120,
      gramaje: 90,
      ladoImprimible: "una_cara",
    },
  },
  {
    id: "laminado_film_v1",
    nombre: "Laminado film",
    descripcion: "Laminado brillo/mate para protección",
    familia: "transferencia_laminacion",
    subfamilia: "laminado_film",
    tipoTecnico: "laminado_film",
    unidadStock: "rollo",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "largo",
        label: "Largo",
        type: "number",
        unit: "m",
        required: true,
      },
      { key: "acabado", label: "Acabado", type: "text", required: true },
      {
        key: "espesor",
        label: "Espesor",
        type: "number",
        unit: "mm",
        optional: true,
      },
      {
        key: "adhesivoTipo",
        label: "Tipo de adhesivo",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo", "acabado"],
    requiredAtributos: ["ancho", "largo", "acabado"],
    atributosIniciales: {
      ancho: 1270,
      largo: 50,
      espesor: 75,
      acabado: "mate",
      adhesivoTipo: "acrilico",
    },
  },
  {
    id: "laminado_pouch_v1",
    nombre: "Laminado pouch",
    descripcion: "Pouch térmico para plastificado en caliente",
    familia: "transferencia_laminacion",
    subfamilia: "laminado_pouch",
    tipoTecnico: "laminado_pouch",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "formatoComercial",
        label: "Formato comercial",
        type: "text",
        required: true,
      },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "margenNoUsable",
        label: "Margen no usable",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "espesor",
        label: "Espesor (micrones)",
        type: "number",
        required: true,
      },
    ],
    dimensionesVariante: ["formatoComercial", "ancho", "alto", "espesor"],
    requiredAtributos: [
      "formatoComercial",
      "ancho",
      "alto",
      "margenNoUsable",
      "espesor",
    ],
    atributosIniciales: {
      formatoComercial: "A4",
      ancho: 216,
      alto: 303,
      margenNoUsable: 3,
      espesor: 125,
    },
  },
  {
    id: "iman_flexible_rollo_v1",
    nombre: "Imán flexible en rollo",
    descripcion:
      "Imán flexible para heladera, souvenirs y piezas promocionales",
    familia: "magnetico_fijacion",
    subfamilia: "iman_ceramico_flexible",
    tipoTecnico: "iman_flexible_rollo",
    unidadStock: "metro_lineal",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "largo",
        label: "Largo",
        type: "number",
        unit: "m",
        required: true,
      },
      {
        key: "espesor",
        label: "Espesor",
        type: "number",
        unit: "mm",
        required: true,
      },
    ],
    dimensionesVariante: ["ancho", "largo", "espesor"],
    requiredAtributos: ["ancho", "largo", "espesor"],
    atributosIniciales: {
      ancho: 610,
      largo: 20,
      espesor: 0.35,
    },
  },
  {
    id: "iman_redondo_v1",
    nombre: "Imán redondo",
    descripcion: "Imán redondo de ferrita, cerámico o neodimio",
    familia: "magnetico_fijacion",
    subfamilia: "iman_ceramico_flexible",
    tipoTecnico: "iman_redondo",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "diametro",
        label: "Diámetro",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "espesor",
        label: "Espesor",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "unidadesPorPack",
        label: "Unidades por pack",
        type: "number",
        required: true,
      },
      { key: "grado", label: "Grado", type: "text", optional: true },
      { key: "adhesivo", label: "Adhesivo", type: "boolean", optional: true },
    ],
    dimensionesVariante: [
      "diametro",
      "espesor",
      "unidadesPorPack",
      "grado",
      "adhesivo",
    ],
    requiredAtributos: ["diametro", "espesor", "unidadesPorPack"],
    atributosIniciales: {
      diametro: 20,
      espesor: 3,
      unidadesPorPack: 100,
      adhesivo: false,
    },
  },
  {
    id: "fijacion_auxiliar_v1",
    nombre: "Tornillo / fijación",
    descripcion:
      "Tornillería y fijaciones auxiliares para cartelería, estructuras y montaje",
    familia: "magnetico_fijacion",
    subfamilia: "fijacion_auxiliar",
    tipoTecnico: "tornillo_autoperforante",
    unidadStock: "unidad",
    unidadCompra: "caja",
    camposTecnicos: [
      {
        key: "tipoFijacion",
        label: "Tipo de fijación",
        type: "text",
        options: ["Tornillo autoperforante", "Tornillo", "Remache", "Otra"],
        required: true,
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        options: [
          "Acero zincado",
          "Acero fosfatado",
          "Acero inoxidable",
          "Otro",
        ],
        required: true,
      },
      { key: "calibre", label: "Calibre", type: "number", required: true },
      {
        key: "largo",
        label: "Largo",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "tipoCabeza",
        label: "Tipo de cabeza",
        type: "text",
        options: ["Tanque / flangeada", "Hexagonal", "Otra"],
        required: true,
      },
      {
        key: "tipoPunta",
        label: "Tipo de punta",
        type: "text",
        options: ["Mecha", "Aguja", "Otra"],
        required: true,
      },
      {
        key: "unidadesPorCaja",
        label: "Unidades por caja",
        type: "number",
        required: true,
      },
    ],
    dimensionesVariante: ["calibre", "largo", "tipoCabeza", "tipoPunta"],
    requiredAtributos: [
      "tipoFijacion",
      "material",
      "calibre",
      "largo",
      "tipoCabeza",
      "tipoPunta",
      "unidadesPorCaja",
    ],
    atributosIniciales: {
      tipoFijacion: "Tornillo autoperforante",
      material: "Acero zincado",
      calibre: 8,
      largo: 12.7,
      tipoCabeza: "Tanque / flangeada",
      tipoPunta: "Mecha",
      encastre: "Phillips #2",
      unidadesPorCaja: 10000,
    },
    defaults: {
      esConsumible: true,
      esRepuesto: false,
      esProductoBase: false,
      lockEsRepuesto: true,
      lockEsProductoBase: true,
    },
  },
  {
    id: "quimico_acabado_v1",
    nombre: "Químico acabado",
    descripcion: "Barniz, primer, promotor de adherencia",
    familia: "quimico_auxiliar",
    subfamilia: "quimico_acabado",
    tipoTecnico: "quimico_acabado",
    unidadStock: "ml",
    unidadCompra: "litro",
    camposTecnicos: [
      {
        key: "volumenPresentacion",
        label: "Volumen de presentación",
        type: "number",
        unit: "ml",
        required: true,
      },
      {
        key: "tecnologiaCompatible",
        label: "Tecnología compatible",
        type: "text",
        required: true,
      },
    ],
    dimensionesVariante: ["volumenPresentacion"],
    requiredAtributos: ["volumenPresentacion", "tecnologiaCompatible"],
    atributosIniciales: {
      volumenPresentacion: 1000,
      tecnologiaCompatible: "impresora_gran_formato_por_area",
      superficiesCompatibles: "acrilico,pvc,vidrio",
    },
  },
  {
    id: "polvo_dtf_v1",
    nombre: "Polvo DTF",
    descripcion: "Polvo adhesivo para proceso DTF",
    familia: "quimico_auxiliar",
    subfamilia: "polvo_dtf",
    tipoTecnico: "polvo_dtf",
    unidadStock: "kg",
    unidadCompra: "kg",
    camposTecnicos: [
      {
        key: "tipoPolvo",
        label: "Tipo de polvo",
        type: "text",
        required: true,
      },
      {
        key: "rangoTemperaturaAplicacion",
        label: "Rango de temperatura",
        type: "text",
        required: true,
      },
    ],
    dimensionesVariante: ["tipoPolvo"],
    requiredAtributos: ["tipoPolvo", "rangoTemperaturaAplicacion"],
    atributosIniciales: {
      tipoPolvo: "hot_melt",
      granulometria: "80-200um",
      rangoTemperaturaAplicacion: "130-160C",
    },
  },
  {
    id: "controlador_led_v1",
    nombre: "Controlador LED",
    descripcion: "Controladores para mono, CCT, RGB y RGBW",
    familia: "electronica_carteleria",
    subfamilia: "controlador_led",
    tipoTecnico: "controlador_led",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "tipoControlador",
        label: "Tipo de controlador",
        type: "text",
        options: ["Mono", "CCT", "RGB", "RGBW"],
        required: true,
      },
      {
        key: "tensionEntrada",
        label: "Tension de entrada",
        type: "number",
        unit: "v",
        required: true,
      },
      { key: "canales", label: "Canales", type: "number", required: true },
      {
        key: "corrienteMaxCanal",
        label: "Corriente maxima por canal",
        type: "number",
        unit: "a",
        required: true,
      },
      {
        key: "corrienteTotalMax",
        label: "Corriente total maxima",
        type: "number",
        unit: "a",
        optional: true,
      },
      {
        key: "protocolo",
        label: "Protocolo",
        type: "text",
        options: ["RF", "Wifi", "DMX", "0-10V", "Bluetooth"],
        optional: true,
      },
    ],
    dimensionesVariante: [
      "tipoControlador",
      "tensionEntrada",
      "canales",
      "corrienteMaxCanal",
    ],
    requiredAtributos: [
      "tipoControlador",
      "tensionEntrada",
      "canales",
      "corrienteMaxCanal",
    ],
    atributosIniciales: {
      tipoControlador: "RGBW",
      tensionEntrada: 24,
      canales: 4,
      corrienteMaxCanal: 5,
      corrienteTotalMax: 20,
      protocolo: "RF",
    },
  },
  {
    id: "neon_flex_led_v1",
    nombre: "Neon flex LED",
    descripcion:
      "Neon flexible LED para carteleria lineal e iluminacion decorativa",
    familia: "neon_luminaria",
    subfamilia: "neon_flex_led",
    tipoTecnico: "neon_flex_led",
    unidadStock: "metro_lineal",
    unidadCompra: "rollo",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "tension",
        label: "Tension",
        type: "number",
        unit: "v",
        required: true,
      },
      {
        key: "potenciaLineal",
        label: "Potencia lineal",
        type: "number",
        unit: "w_m",
        required: true,
      },
      {
        key: "corrienteNominal",
        label: "Corriente nominal",
        type: "number",
        unit: "a",
        optional: true,
      },
      {
        key: "colorLuz",
        label: "Color de luz",
        type: "text",
        options: ["3000K", "4000K", "6500K", "Rojo", "Verde", "Azul", "RGB"],
        required: true,
      },
      {
        key: "ip",
        label: "Grado IP",
        type: "text",
        options: ["IP20", "IP65", "IP67", "IP68"],
        required: true,
      },
    ],
    dimensionesVariante: [
      "ancho",
      "alto",
      "tension",
      "potenciaLineal",
      "colorLuz",
      "ip",
    ],
    requiredAtributos: [
      "ancho",
      "alto",
      "tension",
      "potenciaLineal",
      "colorLuz",
      "ip",
    ],
    atributosIniciales: {
      ancho: 6,
      alto: 12,
      tension: 24,
      potenciaLineal: 10,
      corrienteNominal: 0.42,
      colorLuz: "4000K",
      ip: "IP67",
    },
  },
  {
    id: "accesorio_neon_led_v1",
    nombre: "Accesorio neon LED",
    descripcion:
      "Clips, tapas, conectores y accesorios de montaje para neon flex",
    familia: "neon_luminaria",
    subfamilia: "accesorio_neon_led",
    tipoTecnico: "accesorio_neon_led",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "tipoAccesorio",
        label: "Tipo de accesorio",
        type: "text",
        options: [
          "Clip",
          "Tapa final",
          "Conector recto",
          "Conector L",
          "Conector T",
          "Grapa",
        ],
        required: true,
      },
      {
        key: "anchoCompatible",
        label: "Ancho compatible",
        type: "number",
        unit: "mm",
        optional: true,
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        options: ["Plastico", "Metal", "Silicona"],
        optional: true,
      },
    ],
    dimensionesVariante: ["tipoAccesorio", "anchoCompatible"],
    requiredAtributos: ["tipoAccesorio"],
    atributosIniciales: {
      tipoAccesorio: "Clip",
      anchoCompatible: 8,
      material: "Plastico",
    },
  },
  {
    id: "anillado_encuadernacion_v1",
    nombre: "Anillado encuadernación",
    descripcion: "Espirales y anillos para terminación editorial",
    familia: "terminacion_editorial",
    subfamilia: "anillado_encuadernacion",
    tipoTecnico: "anillado_encuadernacion",
    unidadStock: "unidad",
    unidadCompra: "caja",
    camposTecnicos: [
      {
        key: "tipoAnillo",
        label: "Tipo de anillo",
        type: "text",
        options: ["ESPIRAL_PLASTICO", "WIRE_O"],
        required: true,
      },
      {
        key: "diametro",
        label: "Diámetro",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "capacidadMaxHojas",
        label: "Capacidad (hojas, 80g)",
        type: "number",
        required: true,
      },
      { key: "color", label: "Color", type: "text", required: false },
      { key: "material", label: "Material", type: "text", required: false },
    ],
    // capacidadMaxHojas va como dimensión de variante (numérica, editable por
    // tenant) igual que `gramaje` en el papel o `rendimientoPaginasIso` en el
    // tóner: la capacidad depende del Ø y la ajusta cada imprenta por fabricante.
    dimensionesVariante: [
      "tipoAnillo",
      "diametro",
      "capacidadMaxHojas",
      "color",
    ],
    requiredAtributos: ["tipoAnillo", "diametro", "capacidadMaxHojas"],
    atributosIniciales: {
      tipoAnillo: "ESPIRAL_PLASTICO",
      diametro: 10,
      capacidadMaxHojas: 80,
      material: "PVC",
      color: "negro",
      pasoPerforacion: "4:1",
    },
  },
  {
    id: "tapa_encuadernacion_v1",
    nombre: "Tapa encuadernación",
    descripcion: "Tapas para cuadernos y documentos",
    familia: "terminacion_editorial",
    subfamilia: "tapa_encuadernacion",
    tipoTecnico: "tapa_encuadernacion",
    unidadStock: "unidad",
    unidadCompra: "caja",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "mm",
        required: true,
      },
      { key: "material", label: "Material", type: "text", required: true },
    ],
    dimensionesVariante: ["ancho", "alto", "material"],
    requiredAtributos: ["ancho", "alto", "material"],
    atributosIniciales: {
      ancho: 210,
      alto: 297,
      material: "polipropileno",
      espesor: 0.5,
      colorBase: "transparente",
    },
  },
  {
    id: "componente_carpeta_v1",
    nombre: "Componente para carpeta",
    descripcion:
      "Solapas, bolsillos y piezas compradas para armado de carpetas.",
    familia: "terminacion_editorial",
    subfamilia: "componente_editorial",
    tipoTecnico: "componente_carpeta",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "tipoComponente",
        label: "Tipo",
        type: "text",
        options: ["Solapa", "Bolsillo", "Portatarjeta", "Refuerzo", "Otro"],
        required: true,
      },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "mm",
        required: true,
      },
      { key: "material", label: "Material", type: "text", required: true },
      { key: "color", label: "Color", type: "text", optional: true },
    ],
    dimensionesVariante: [
      "tipoComponente",
      "ancho",
      "alto",
      "material",
      "color",
    ],
    requiredAtributos: ["tipoComponente", "ancho", "alto", "material"],
    atributosIniciales: {
      tipoComponente: "Solapa",
      ancho: 210,
      alto: 90,
      material: "cartulina",
      color: "blanco",
    },
  },
  {
    id: "componente_editorial_v1",
    nombre: "Componente editorial",
    descripcion:
      "Insumos de terminación editorial y emblocado por unidad: ganchos, broches y piezas compradas.",
    familia: "terminacion_editorial",
    subfamilia: "componente_editorial",
    tipoTecnico: "componente_editorial",
    unidadStock: "unidad",
    unidadCompra: "caja",
    camposTecnicos: [
      { key: "material", label: "Material", type: "text", required: true },
      { key: "medida", label: "Medida", type: "text", optional: true },
      {
        key: "unidadesPorCaja",
        label: "Unidades por caja",
        type: "number",
        optional: true,
      },
    ],
    dimensionesVariante: [
      "medida",
      "hojasDesde",
      "hojasHasta",
      "unidadesPorCaja",
      "material",
      "color",
    ],
    requiredAtributos: ["material"],
    atributosIniciales: {
      material: "alambre metálico",
    },
  },
  {
    id: "componente_editorial_hoja_v1",
    nombre: "Componente editorial en hoja",
    descripcion:
      "Componentes de emblocado que se compran en hojas/pliegos: cartón de contratapa, láminas de terminación.",
    familia: "terminacion_editorial",
    subfamilia: "componente_editorial",
    tipoTecnico: "componente_editorial_hoja",
    unidadStock: "hoja",
    unidadCompra: "pack",
    camposTecnicos: [
      { key: "material", label: "Material", type: "text", required: true },
    ],
    dimensionesVariante: ["formatoComercial", "ancho", "alto", "color"],
    requiredAtributos: ["material"],
    atributosIniciales: {
      material: "cartón gris",
    },
  },
  {
    id: "pegatina_raspadita_v1",
    nombre: "Pegatina raspadita",
    descripcion:
      "Pegatina autoadhesiva con recubrimiento raspable, aplicada por unidad sobre piezas impresas.",
    familia: "terminacion_editorial",
    subfamilia: "pegatina_raspadita",
    tipoTecnico: "pegatina_raspadita",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "forma",
        label: "Forma",
        type: "text",
        options: ["Rectangular", "Circular", "Ovalada", "Otra"],
        optional: true,
      },
      { key: "color", label: "Color", type: "text", optional: true },
      {
        key: "unidadesPorPack",
        label: "Unidades por pack",
        type: "number",
        optional: true,
      },
    ],
    dimensionesVariante: ["ancho", "alto", "forma", "color"],
    requiredAtributos: ["ancho", "alto"],
    atributosIniciales: {
      ancho: 40,
      alto: 10,
      forma: "Rectangular",
      color: "plateado",
      unidadesPorPack: 100,
    },
    defaults: {
      esConsumible: true,
      esRepuesto: false,
      esProductoBase: false,
      lockEsRepuesto: true,
      lockEsProductoBase: true,
    },
  },
  {
    id: "argolla_llavero_accesorio_v1",
    nombre: "Argolla llavero",
    descripcion: "Herrajes para llaveros promocionales",
    familia: "herraje_accesorio",
    subfamilia: "argolla_llavero_accesorio",
    tipoTecnico: "argolla_llavero",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "diametro",
        label: "Diámetro",
        type: "number",
        unit: "mm",
        required: true,
      },
      { key: "material", label: "Material", type: "text", required: true },
    ],
    dimensionesVariante: ["diametro", "material"],
    requiredAtributos: ["diametro", "material"],
    atributosIniciales: {
      diametro: 25,
      material: "acero",
      terminacion: "niquelado",
    },
  },
  {
    id: "ojal_ojalillo_remache_v1",
    nombre: "Ojal / ojalillo",
    descripcion: "Ojales para lona, banners y cartelería",
    familia: "herraje_accesorio",
    subfamilia: "ojal_ojalillo_remache",
    tipoTecnico: "ojal",
    unidadStock: "unidad",
    unidadCompra: "caja",
    camposTecnicos: [
      {
        key: "diametroInterno",
        label: "Diámetro interno",
        type: "number",
        unit: "mm",
        required: true,
      },
      { key: "material", label: "Material", type: "text", required: true },
    ],
    dimensionesVariante: ["diametroInterno", "material"],
    requiredAtributos: ["diametroInterno", "material"],
    atributosIniciales: {
      diametroInterno: 10,
      material: "laton",
      terminado: "niquelado",
    },
  },
  {
    id: "embalaje_proteccion_v1",
    nombre: "Embalaje / protección",
    descripcion: "Bolsas, cajas, sobres y protecciones para entrega.",
    familia: "terminacion_editorial",
    subfamilia: "embalaje_proteccion",
    tipoTecnico: "embalaje_proteccion",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      {
        key: "tipoEmbalaje",
        label: "Tipo",
        type: "text",
        options: ["Bolsa", "Caja", "Sobre", "Faja", "Protección"],
        required: true,
      },
      {
        key: "capacidadUnidades",
        label: "Capacidad",
        type: "number",
        required: true,
      },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "cm",
        optional: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "cm",
        optional: true,
      },
      { key: "material", label: "Material", type: "text", optional: true },
    ],
    dimensionesVariante: [
      "tipoEmbalaje",
      "capacidadUnidades",
      "ancho",
      "alto",
      "material",
    ],
    requiredAtributos: ["tipoEmbalaje", "capacidadUnidades"],
    atributosIniciales: {
      tipoEmbalaje: "Bolsa",
      capacidadUnidades: 100,
      material: "Celofán",
    },
  },
  {
    id: "portabanner_estructura_v1",
    nombre: "Portabanner estructura",
    descripcion: "Estructuras roll-up, X, L o pop-up",
    familia: "pop_exhibidor",
    subfamilia: "portabanner_estructura",
    tipoTecnico: "portabanner",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "tipoPortabanner",
        label: "Tipo de portabanner",
        type: "text",
        required: true,
      },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "cm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "cm",
        required: true,
      },
    ],
    dimensionesVariante: ["tipoPortabanner", "ancho", "alto"],
    requiredAtributos: ["tipoPortabanner", "ancho", "alto"],
    atributosIniciales: {
      tipoPortabanner: "rollup",
      ancho: 85,
      alto: 200,
      materialEstructura: "aluminio",
    },
  },
  {
    id: "repuesto_impresion_v1",
    nombre: "Repuesto técnico impresión",
    descripcion:
      "Repuestos para equipos de impresión (láser, UV, DTF, solvente, latex, sublimación).",
    familia: "quimico_auxiliar",
    subfamilia: "auxiliar_proceso",
    tipoTecnico: "repuesto_impresion",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "tipoComponenteDesgaste",
        label: "Tipo de componente",
        type: "text",
        options: [...REPLACEMENT_COMPONENT_OPTIONS],
        required: true,
      },
      {
        key: "plantillasCompatibles",
        label: "Plantillas compatibles",
        type: "text",
        options: MAQUINARIA_TEMPLATE_OPTIONS,
        required: true,
      },
      {
        key: "unidadVidaUtil",
        label: "Unidad de vida útil",
        type: "text",
        options: REPLACEMENT_WEAR_UNIT_OPTIONS,
        required: true,
      },
      {
        key: "vidaUtilReferencia",
        label: "Vida útil de referencia",
        type: "number",
        required: true,
      },
      {
        key: "cantidadPorRecambio",
        label: "Cantidad por recambio",
        type: "number",
        optional: true,
      },
      {
        key: "maquinasCompatibles",
        label: "Maquinas compatibles",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: [
      "tipoComponenteDesgaste",
      "plantillasCompatibles",
      "vidaUtilReferencia",
      "unidadVidaUtil",
      "cantidadPorRecambio",
      "maquinasCompatibles",
    ],
    requiredAtributos: [
      "tipoComponenteDesgaste",
      "plantillasCompatibles",
      "unidadVidaUtil",
      "vidaUtilReferencia",
    ],
    atributosIniciales: {
      categoriaRepuesto: "desgaste",
      clasificacion: "tecnico_maquinaria",
    },
    defaults: {
      esConsumible: false,
      esRepuesto: true,
      lockEsConsumible: false,
      lockEsRepuesto: true,
    },
  },
  {
    id: "repuesto_corte_mecanizado_v1",
    nombre: "Repuesto técnico corte/mecanizado",
    descripcion:
      "Repuestos para CNC, láser de corte, mesa de corte y plotter de corte.",
    familia: "quimico_auxiliar",
    subfamilia: "auxiliar_proceso",
    tipoTecnico: "repuesto_corte_mecanizado",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "tipoComponenteDesgaste",
        label: "Tipo de componente",
        type: "text",
        options: [...REPLACEMENT_COMPONENT_OPTIONS],
        required: true,
      },
      {
        key: "plantillasCompatibles",
        label: "Plantillas compatibles",
        type: "text",
        options: MAQUINARIA_TEMPLATE_OPTIONS,
        required: true,
      },
      {
        key: "unidadVidaUtil",
        label: "Unidad de vida útil",
        type: "text",
        options: REPLACEMENT_WEAR_UNIT_OPTIONS,
        required: true,
      },
      {
        key: "vidaUtilReferencia",
        label: "Vida útil de referencia",
        type: "number",
        required: true,
      },
      {
        key: "cantidadPorRecambio",
        label: "Cantidad por recambio",
        type: "number",
        optional: true,
      },
      {
        key: "materialTrabajo",
        label: "Material de trabajo dominante",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: [
      "tipoComponenteDesgaste",
      "plantillasCompatibles",
      "vidaUtilReferencia",
      "unidadVidaUtil",
      "cantidadPorRecambio",
      "materialTrabajo",
    ],
    requiredAtributos: [
      "tipoComponenteDesgaste",
      "plantillasCompatibles",
      "unidadVidaUtil",
      "vidaUtilReferencia",
    ],
    atributosIniciales: {
      categoriaRepuesto: "desgaste",
      clasificacion: "tecnico_maquinaria",
    },
    defaults: {
      esConsumible: false,
      esRepuesto: true,
      lockEsConsumible: false,
      lockEsRepuesto: true,
    },
  },
  {
    id: "sello_automatico_v1",
    nombre: "Sello automático",
    descripcion:
      "Sello autoentintable con carcasa y almohadilla integrada (Colop Printer, Trodat Printy, Nykon).",
    familia: "sellos",
    subfamilia: "sellos_automaticos",
    tipoTecnico: "sello_automatico",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "marca",
        label: "Marca",
        type: "text",
        options: ["Colop", "Trodat", "Nykon", "Otro"],
        required: true,
      },
      { key: "modelo", label: "Modelo", type: "text", required: true },
      {
        key: "anchoPolimero",
        label: "Ancho de polímero",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "altoPolimero",
        label: "Alto de polímero",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "lineasTexto",
        label: "Líneas de texto (máx.)",
        type: "number",
        required: true,
      },
      {
        key: "forma",
        label: "Forma",
        type: "text",
        options: ["Rectangular", "Redondo", "Ovalado"],
        optional: true,
      },
      {
        key: "colorCarcasa",
        label: "Color de carcasa",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: [
      "marca",
      "modelo",
      "anchoPolimero",
      "altoPolimero",
      "lineasTexto",
      "forma",
      "colorCarcasa",
    ],
    requiredAtributos: [
      "marca",
      "modelo",
      "anchoPolimero",
      "altoPolimero",
      "lineasTexto",
    ],
    atributosIniciales: {
      marca: "Colop",
      modelo: "Printer 30",
      anchoPolimero: 47,
      altoPolimero: 18,
      lineasTexto: 5,
      forma: "Rectangular",
    },
  },
  {
    id: "sello_manual_v1",
    nombre: "Sello manual",
    descripcion:
      "Sello tradicional con mango (madera o plástico); usa almohadilla aparte.",
    familia: "sellos",
    subfamilia: "sellos_manuales",
    tipoTecnico: "sello_manual",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "marca",
        label: "Marca",
        type: "text",
        options: ["Colop", "Trodat", "Nykon", "Otro"],
        required: true,
      },
      { key: "modelo", label: "Modelo", type: "text", required: true },
      {
        key: "anchoPolimero",
        label: "Ancho de polímero",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "altoPolimero",
        label: "Alto de polímero",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "lineasTexto",
        label: "Líneas de texto (máx.)",
        type: "number",
        required: true,
      },
      {
        key: "forma",
        label: "Forma",
        type: "text",
        options: ["Rectangular", "Redondo", "Ovalado"],
        optional: true,
      },
      {
        key: "material",
        label: "Material del mango",
        type: "text",
        options: ["Madera", "Plástico"],
        optional: true,
      },
    ],
    dimensionesVariante: [
      "marca",
      "modelo",
      "anchoPolimero",
      "altoPolimero",
      "lineasTexto",
      "forma",
      "material",
    ],
    requiredAtributos: [
      "marca",
      "modelo",
      "anchoPolimero",
      "altoPolimero",
      "lineasTexto",
    ],
    atributosIniciales: {
      marca: "Trodat",
      modelo: "Mango madera 40 mm",
      anchoPolimero: 40,
      altoPolimero: 40,
      lineasTexto: 4,
      forma: "Rectangular",
      material: "Madera",
    },
  },
  {
    id: "almohadilla_sello_v1",
    nombre: "Repuesto de almohadilla de sello",
    descripcion:
      "Almohadilla de recambio para sellos automáticos, específica por modelo (ej. 6/4911 para Printy 4911).",
    familia: "sellos",
    subfamilia: "almohadilla_tinta",
    tipoTecnico: "almohadilla_sello",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "marca",
        label: "Marca",
        type: "text",
        options: ["Trodat", "Colop", "Nykon", "Otro"],
        required: true,
      },
      {
        key: "codigoRepuesto",
        label: "Código de repuesto",
        type: "text",
        required: true,
      },
      {
        key: "modeloCompatible",
        label: "Modelo de sello compatible",
        type: "text",
        optional: true,
      },
      {
        key: "colorTinta",
        label: "Color de tinta",
        type: "text",
        options: [
          "Negro",
          "Azul",
          "Rojo",
          "Verde",
          "Violeta",
          "Neutro",
          "MCI",
          "Bicolor",
        ],
        required: true,
      },
    ],
    dimensionesVariante: ["codigoRepuesto", "colorTinta", "modeloCompatible"],
    requiredAtributos: ["marca", "codigoRepuesto", "colorTinta"],
    atributosIniciales: {
      marca: "Trodat",
      codigoRepuesto: "6/4911",
      modeloCompatible: "Printy 4911",
      colorTinta: "Negro",
    },
    defaults: {
      esConsumible: true,
      esRepuesto: false,
      lockEsConsumible: false,
      lockEsRepuesto: false,
    },
  },
  {
    id: "tinta_sello_v1",
    nombre: "Tinta para sellos",
    descripcion:
      "Tinta de recarga para almohadillas de sellos (frascos), por color y volumen.",
    familia: "sellos",
    subfamilia: "almohadilla_tinta",
    tipoTecnico: "tinta_sello",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "marca",
        label: "Marca",
        type: "text",
        options: ["Trodat", "Colop", "Nykon", "Otro"],
        required: true,
      },
      { key: "referencia", label: "Referencia", type: "text", required: true },
      {
        key: "colorTinta",
        label: "Color de tinta",
        type: "text",
        options: ["Negro", "Azul", "Rojo", "Verde", "Violeta"],
        required: true,
      },
      {
        key: "volumen",
        label: "Volumen",
        type: "number",
        unit: "ml",
        required: true,
      },
      {
        key: "uso",
        label: "Uso",
        type: "text",
        options: ["General", "Telas"],
        optional: true,
      },
    ],
    dimensionesVariante: ["referencia", "colorTinta", "volumen", "uso"],
    requiredAtributos: ["marca", "referencia", "colorTinta", "volumen"],
    atributosIniciales: {
      marca: "Trodat",
      referencia: "7011",
      colorTinta: "Negro",
      volumen: 28,
      uso: "General",
    },
    defaults: {
      esConsumible: true,
      esRepuesto: false,
      lockEsConsumible: false,
      lockEsRepuesto: false,
    },
  },
  {
    id: "almohadilla_escritorio_v1",
    nombre: "Almohadilla de escritorio",
    descripcion:
      "Tampón de escritorio para sellos manuales (entintado externo), por tamaño y color de tinta.",
    familia: "sellos",
    subfamilia: "almohadilla_tinta",
    tipoTecnico: "almohadilla_escritorio",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "marca",
        label: "Marca",
        type: "text",
        options: ["Trodat", "Colop", "Nykon", "Otro"],
        required: true,
      },
      { key: "referencia", label: "Referencia", type: "text", required: true },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "cm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "cm",
        required: true,
      },
      {
        key: "colorTinta",
        label: "Color de tinta",
        type: "text",
        options: ["Negro", "Azul", "Rojo", "Verde", "Neutro"],
        required: true,
      },
      {
        key: "uso",
        label: "Uso",
        type: "text",
        options: ["Escritorio", "Dactilar"],
        optional: true,
      },
    ],
    dimensionesVariante: ["referencia", "ancho", "alto", "colorTinta", "uso"],
    requiredAtributos: ["marca", "referencia", "ancho", "alto", "colorTinta"],
    atributosIniciales: {
      marca: "Trodat",
      referencia: "N9052",
      ancho: 11,
      alto: 7,
      colorTinta: "Negro",
      uso: "Escritorio",
    },
    defaults: {
      esConsumible: true,
      esRepuesto: false,
      lockEsConsumible: false,
      lockEsRepuesto: false,
    },
  },
  {
    id: "goma_laserable_v1",
    nombre: "Goma laserable",
    descripcion:
      "Plancha de goma/fotopolímero para grabar con láser y cortar al tamaño del sello. Se consume por área.",
    familia: "sellos",
    subfamilia: "goma_laserable",
    tipoTecnico: "goma_laserable",
    unidadStock: "hoja",
    unidadCompra: "hoja",
    camposTecnicos: [
      { key: "marca", label: "Marca", type: "text", optional: true },
      {
        key: "color",
        label: "Color",
        type: "text",
        options: ["Rojo", "Verde", "Gris", "Otro"],
        required: true,
      },
      {
        key: "espesor",
        label: "Espesor",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "ancho",
        label: "Ancho",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "alto",
        label: "Alto",
        type: "number",
        unit: "mm",
        required: true,
      },
    ],
    dimensionesVariante: ["color", "espesor", "ancho", "alto", "marca"],
    requiredAtributos: ["color", "espesor", "ancho", "alto"],
    atributosIniciales: {
      color: "Rojo",
      espesor: 2.3,
      ancho: 210,
      alto: 297,
    },
  },
  {
    id: "objeto_promocional_base_v1",
    nombre: "Objeto promocional (blank)",
    descripcion:
      "Artículo comprado por unidad para decorar (taza, botella, mousepad, cuaderno). No es un insumo de producción: su costo entra por unidad. La medida de la estampa la maneja la personalización, no este material. Ver docs/productos-comprados-merchandising-diseno.md",
    familia: "sustrato",
    subfamilia: "objeto_promocional_base",
    tipoTecnico: "objeto_promocional_base",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "categoria",
        label: "Categoría",
        type: "text",
        options: [
          "Drinkware",
          "Escritura",
          "Oficina",
          "Tecnología",
          "Llavería",
          "Hogar y bazar",
          "Bolsos y estuches",
          "Escolar",
          "Salud",
          "Automotor",
          "Regalería",
        ],
        required: true,
      },
      {
        key: "tipoObjeto",
        label: "Tipo de objeto",
        type: "text",
        options: [
          "Taza",
          "Botella",
          "Termo",
          "Vaso",
          "Mate",
          "Mousepad",
          "Llavero",
          "Lapicera",
          "Cuaderno",
          "Agenda",
          "Posavasos",
          "Otro",
        ],
        required: true,
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        options: [
          "Cerámica",
          "Vidrio",
          "Plástico",
          "Metal",
          "Acero inoxidable",
          "Aluminio",
          "Madera",
          "Silicona",
          "Otro",
        ],
        required: true,
      },
      {
        key: "capacidad",
        label: "Capacidad",
        type: "number",
        unit: "ml",
        optional: true,
      },
      { key: "color", label: "Color", type: "text", optional: true },
      {
        key: "modelo",
        label: "Modelo/Descripción",
        type: "text",
        optional: true,
      },
    ],
    dimensionesVariante: [
      "tipoObjeto",
      "material",
      "color",
      "modelo",
      "capacidad",
    ],
    requiredAtributos: ["categoria", "tipoObjeto", "material"],
    atributosIniciales: {
      categoria: "Drinkware",
      tipoObjeto: "Taza",
      material: "Cerámica",
      capacidad: 350,
      color: "Blanco",
    },
    defaults: {
      esConsumible: false,
      esRepuesto: false,
      esProductoBase: true,
      lockEsProductoBase: true,
    },
  },
  {
    id: "textil_indumentaria_v1",
    nombre: "Textil / indumentaria (blank)",
    descripcion:
      "Prenda comprada por unidad para estampar/bordar (remera, buzo, gorra, tote bag). Se compra por unidad; talle y color son variantes, normalmente al mismo precio. La estampa la maneja la personalización. Ver docs/productos-comprados-merchandising-diseno.md",
    familia: "sustrato",
    subfamilia: "textil_indumentaria",
    tipoTecnico: "textil_indumentaria",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      {
        key: "categoria",
        label: "Categoría",
        type: "text",
        options: [
          "Remeras",
          "Camisas y chombas",
          "Buzos y abrigo",
          "Camperas",
          "Gorras y sombreros",
          "Bolsos de tela",
          "Indumentaria de trabajo",
          "Bebé y niños",
          "Deportivo",
          "Hogar textil",
          "Accesorios",
        ],
        required: true,
      },
      {
        key: "tipoPrenda",
        label: "Tipo de prenda",
        type: "text",
        options: [
          "Remera",
          "Remera manga larga",
          "Musculosa",
          "Chomba",
          "Camisa",
          "Buzo canguro",
          "Buzo cerrado",
          "Campera",
          "Gorra",
          "Tote bag",
          "Otro",
        ],
        required: true,
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        options: [
          "Algodón",
          "Poliéster",
          "Mixta (poly/algodón)",
          "Frisa",
          "Piqué",
          "Otro",
        ],
        required: true,
      },
      { key: "color", label: "Color", type: "text", required: true },
      {
        key: "talle",
        label: "Talle",
        type: "text",
        options: ["Único", "XS", "S", "M", "L", "XL", "XXL", "XXXL"],
        required: true,
      },
      {
        key: "gramaje",
        label: "Gramaje",
        type: "number",
        unit: "g_m2",
        optional: true,
      },
      { key: "marca", label: "Marca", type: "text", optional: true },
    ],
    dimensionesVariante: [
      "tipoPrenda",
      "material",
      "color",
      "talle",
      "gramaje",
      "marca",
    ],
    requiredAtributos: [
      "categoria",
      "tipoPrenda",
      "material",
      "color",
      "talle",
    ],
    atributosIniciales: {
      categoria: "Remeras",
      tipoPrenda: "Remera",
      material: "Algodón",
      color: "Blanco",
      talle: "M",
    },
    defaults: {
      esConsumible: false,
      esRepuesto: false,
      esProductoBase: true,
      lockEsProductoBase: true,
    },
  },
  // ── F1 cartelería (docs/carteleria-configurador-diseno.md) ──
  // cobertura (m²) y paso (mm) son atributos DE LA VARIANTE porque cada módulo
  // ilumina distinto: el motor los lee para derivar la cantidad sembrada.
  {
    id: "modulo_led_carteleria_v1",
    nombre: "Módulo LED de cartelería",
    descripcion: "Módulo LED para backlight, corpóreas y light box",
    familia: "electronica_carteleria",
    subfamilia: "modulo_led_carteleria",
    tipoTecnico: "modulo_led_carteleria",
    unidadStock: "unidad",
    unidadCompra: "pack",
    camposTecnicos: [
      { key: "modelo", label: "Modelo", type: "text", required: true },
      {
        key: "potencia",
        label: "Potencia por módulo",
        type: "number",
        unit: "w",
        required: true,
      },
      {
        key: "tension",
        label: "Tensión",
        type: "text",
        options: ["12V", "24V", "220V"],
        required: true,
      },
      // `paso` es LA perilla del sembrado ("cada cuánto va un LED"): en área
      // arma la grilla ceil(ancho/paso)×ceil(alto/paso); en recorrido, el
      // espaciado sobre el trazo. `cobertura` (m²/módulo) quedó como atributo
      // legacy que el motor acepta de fallback pero ya no se edita acá.
      {
        key: "paso",
        label: "Paso entre módulos",
        type: "number",
        unit: "mm",
        preferredDisplayUnit: "cm",
        required: true,
      },
      {
        key: "temperaturaColor",
        label: "Temperatura de color",
        type: "text",
        options: ["Cálido", "Neutro", "Frío"],
        required: false,
      },
    ],
    dimensionesVariante: [
      "modelo",
      "potencia",
      "tension",
      "paso",
      "temperaturaColor",
    ],
    requiredAtributos: ["modelo", "potencia", "tension", "paso"],
    atributosIniciales: {
      modelo: "SMD 2835 x3",
      potencia: 0.72,
      tension: "12V",
      paso: 250,
      temperaturaColor: "Frío",
    },
  },
  {
    id: "fuente_alimentacion_led_v1",
    nombre: "Fuente de alimentación LED",
    descripcion:
      "Fuente switching para cartelería luminosa (el motor elige por capacidad)",
    familia: "electronica_carteleria",
    subfamilia: "fuente_alimentacion_led",
    tipoTecnico: "fuente_alimentacion_led",
    unidadStock: "unidad",
    unidadCompra: "unidad",
    camposTecnicos: [
      // Las fuentes se COMPRAN por amperes; la capacidad en W (que usa el
      // selector MENOR_CAPACIDAD del motor contra los watts derivados) se
      // calcula sola al guardar: capacidad = corriente × tensión
      // (normalizeVarianteAtributos de la ficha). `capacidad` sigue viva
      // como atributo pero ya no se edita a mano.
      {
        key: "corriente",
        label: "Corriente",
        type: "number",
        unit: "a",
        required: true,
      },
      {
        key: "tension",
        label: "Tensión de salida",
        type: "text",
        options: ["12V", "24V"],
        required: true,
      },
      {
        key: "proteccion",
        label: "Protección",
        type: "text",
        options: ["IP20", "IP65", "IP67"],
        required: false,
      },
    ],
    dimensionesVariante: ["corriente", "tension", "proteccion"],
    requiredAtributos: ["corriente", "tension"],
    atributosIniciales: {
      corriente: 12.5,
      tension: "12V",
      proteccion: "IP67",
      capacidad: 150,
    },
  },
  {
    id: "cableado_conectica_v1",
    nombre: "Cable y conectores",
    descripcion: "Cable de baja tensión y conectores para cartelería",
    familia: "electronica_carteleria",
    subfamilia: "cableado_conectica",
    tipoTecnico: "cableado_conectica",
    unidadStock: "metro_lineal",
    unidadCompra: "rollo",
    camposTecnicos: [
      { key: "seccion", label: "Sección", type: "text", required: true },
      {
        key: "tipo",
        label: "Tipo",
        type: "text",
        options: ["Cable taller", "Unipolar", "Conector fast"],
        required: false,
      },
    ],
    dimensionesVariante: ["seccion", "tipo"],
    requiredAtributos: ["seccion"],
    atributosIniciales: {
      seccion: "2×1 mm²",
      tipo: "Cable taller",
    },
  },
  {
    id: "perfil_estructural_v1",
    nombre: "Perfil / caño estructural",
    descripcion:
      "Caño, perfil o listón para bastidores de cartelería (metal o madera)",
    familia: "metal_estructura",
    subfamilia: "perfil_estructural",
    tipoTecnico: "perfil_estructural",
    unidadStock: "metro_lineal",
    unidadCompra: "unidad",
    camposTecnicos: [
      { key: "seccion", label: "Sección", type: "text", required: true },
      {
        key: "espesor",
        label: "Espesor de pared",
        type: "number",
        unit: "mm",
        required: false,
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        options: ["Acero", "Aluminio", "Galvanizado", "Madera"],
        required: true,
      },
      {
        key: "desarrolloSeccion",
        label: "Desarrollo de la sección (m²/ml, para pintura)",
        type: "number",
        unit: "m2",
        required: false,
      },
      {
        key: "largoBarra",
        label: "Largo de la barra comercial (se cobran barras enteras)",
        type: "number",
        unit: "m",
        required: false,
      },
    ],
    dimensionesVariante: ["seccion", "material", "espesor"],
    requiredAtributos: ["seccion", "material"],
    atributosIniciales: {
      seccion: "40×40 mm",
      espesor: 1.6,
      material: "Acero",
      desarrolloSeccion: 0.16,
    },
  },
  {
    id: "chapa_metalica_v1",
    nombre: "Chapa metálica",
    descripcion: "Chapa para cenefas, fondos y plegados de cartelería",
    familia: "metal_estructura",
    subfamilia: "chapa_metalica",
    tipoTecnico: "chapa_metalica",
    unidadStock: "m2",
    unidadCompra: "hoja",
    camposTecnicos: [
      {
        key: "tipo",
        label: "Tipo",
        type: "text",
        options: ["Galvanizada", "Prepintada", "Aluminio", "Inoxidable"],
        required: true,
      },
      {
        key: "espesor",
        label: "Espesor",
        type: "number",
        unit: "mm",
        required: true,
      },
      // La chapa se compra en hoja con medida (1220×2440) o se carga como
      // tarifa por m² sin presentación: sin estos campos, dos variantes del
      // mismo tipo+espesor se ven idénticas en el selector. Las keys llevan
      // Mm porque el motor lee `anchoMm`/`altoMm` de los atributos para el
      // nesting de la hoja (allowUnitSuffixKeys).
      {
        key: "presentacion",
        label: "Presentación",
        type: "text",
        options: ["hoja"],
        optional: true,
      },
      {
        key: "anchoMm",
        label: "Ancho",
        type: "number",
        unit: "mm",
        optional: true,
      },
      {
        key: "altoMm",
        label: "Alto",
        type: "number",
        unit: "mm",
        optional: true,
      },
    ],
    dimensionesVariante: [
      "tipo",
      "espesor",
      "presentacion",
      "anchoMm",
      "altoMm",
    ],
    requiredAtributos: ["tipo", "espesor"],
    atributosIniciales: {
      tipo: "Galvanizada",
      espesor: 0.7,
    },
    allowUnitSuffixKeys: ["anchoMm", "altoMm"],
  },
];

export const materiaPrimaTemplatesMap = new Map(
  materiaPrimaTemplatesV1.map((template) => [template.id, template]),
);

const LEGACY_TEMPLATE_ALIASES: Record<string, string> = {
  papel_hoja: "sustrato_hoja_v1",
  vinilo_rollo: "sustrato_rollo_flexible_v1",
  rigido_placa: "sustrato_rigido_v1",
  film_laminado: "laminado_film_v1",
  embalaje: "embalaje_proteccion_v1",
};

for (const template of materiaPrimaTemplatesV1) {
  const fieldKeys = template.camposTecnicos.map((field) => field.key);
  assertCanonicalTemplateKeys(template.id, fieldKeys, {
    allowUnitSuffixKeys: template.allowUnitSuffixKeys,
  });
  assertAnchoAntesDeAlto(template.id, template.dimensionesVariante);
}

export function getMateriaPrimaTemplate(templateId: string) {
  return (
    materiaPrimaTemplatesMap.get(templateId) ??
    materiaPrimaTemplatesMap.get(LEGACY_TEMPLATE_ALIASES[templateId] ?? "") ??
    null
  );
}

export function getReplacementComponentLabel(value: string) {
  return REPLACEMENT_COMPONENT_LABELS[value] ?? value;
}

export function getReplacementComponentOptionsForTemplates(
  templateIds: string[],
) {
  const normalizedTemplateIds = templateIds
    .map((item) => item.trim())
    .filter(
      (item): item is PlantillaMaquinaria =>
        item in REPLACEMENT_COMPONENT_OPTIONS_BY_TEMPLATE,
    );
  if (normalizedTemplateIds.length === 0) {
    return [...REPLACEMENT_COMPONENT_OPTIONS];
  }
  const allowed = new Set<string>();
  for (const templateId of normalizedTemplateIds) {
    for (const componentType of REPLACEMENT_COMPONENT_OPTIONS_BY_TEMPLATE[
      templateId
    ]) {
      allowed.add(componentType);
    }
  }
  return REPLACEMENT_COMPONENT_OPTIONS.filter((item) => allowed.has(item));
}

export function getMateriaPrimaTemplateAvailability(templateId: string) {
  const template = getMateriaPrimaTemplate(templateId);
  return {
    esConsumible: template?.defaults?.esConsumible ?? false,
    esRepuesto: template?.defaults?.esRepuesto ?? false,
    esProductoBase: template?.defaults?.esProductoBase ?? false,
    lockEsConsumible: template?.defaults?.lockEsConsumible ?? false,
    lockEsRepuesto: template?.defaults?.lockEsRepuesto ?? false,
    lockEsProductoBase: template?.defaults?.lockEsProductoBase ?? false,
  };
}
