import type { VistaClave } from "./permisos-vistas";
export const RUTAS_VISTAS: Record<string, VistaClave> = {
  "/comercial/crear-propuesta": "comercial.ordenes",
  "/comercial/presupuestos": "comercial.presupuestos",
  "/comercial/campanas": "comercial.campanas",
  "/produccion/ordenes": "comercial.ordenes",
  "/comercial/centro-copiado": "comercial.copiado",
  "/crm/clientes": "crm.clientes",
  "/clientes": "crm.clientes",
  "/crm/cupones": "crm.cupones",
  "/crm/fidelizacion": "crm.fidelizacion",
  "/proveedores": "registros.proveedores",
  "/empleados": "registros.empleados",
  "/costos/centros-de-costo": "costos.centros",
  "/costos/maquinaria": "costos.maquinaria",
  "/productos-servicios/pasos": "costos.nodos",
  "/productos-servicios/rutas": "costos.flujos",
  "/productos-servicios/cargos-directos": "costos.cargos",
  "/productos-servicios": "costos.catalogo",
  "/produccion/tablero": "produccion.tablero",
  "/produccion/planificacion": "produccion.planificacion",
  "/produccion/colas": "produccion.colas",
  "/produccion/estaciones": "produccion.estaciones",
  "/administracion/tesoreria": "administracion.tesoreria",
  "/administracion/deudores": "administracion.cobrar",
  "/administracion/acreditaciones": "administracion.cobrar",
  "/administracion/cuentas-por-pagar": "administracion.pagar",
  "/administracion/egresos": "administracion.egresos",
  "/administracion/gastos-fijos": "administracion.gastos",
  "/administracion/programaciones": "administracion.gastos",
  "/administracion/comprobantes": "administracion.comprobantes",
  "/administracion/facturacion": "administracion.facturacion",
  "/inventario/materias-primas": "inventario.materiales",
  "/inventario/centro-stock": "inventario.stock",
  "/inventario/compras": "inventario.compras",
  "/inventario/movimientos": "inventario.movimientos",
  "/configuracion/empresa": "configuracion.empresa",
  "/configuracion/usuarios": "configuracion.usuarios",
  "/configuracion/datos-fiscales": "configuracion.fiscal",
  "/configuracion/metodos-pago": "configuracion.metodos",
  "/configuracion/impuestos": "configuracion.impuestos",
  "/configuracion/comisiones": "configuracion.comisiones",
  "/configuracion/centro-copiado": "configuracion.copiado",
  "/configuracion/impresoras": "configuracion.impresoras",
  "/configuracion/almacenamiento": "configuracion.almacenamiento",
  "/configuracion/integraciones": "configuracion.integraciones",
  "/suscripcion": "configuracion.suscripcion",
  "/reportes/resumen": "reportes.resumen",
  "/reportes/comercial": "reportes.comercial",
  "/reportes/embudo": "reportes.embudo",
  "/reportes/clientes": "reportes.clientes",
  "/reportes/produccion": "reportes.produccion",
  "/reportes/salud-eta": "reportes.salud_eta",
  "/reportes/equipo": "reportes.equipo",
  "/reportes/finanzas": "reportes.finanzas",
  "/reportes/producto": "reportes.producto",
};

export function vistaDeRuta(ruta: string): VistaClave | null {
  const base = Object.keys(RUTAS_VISTAS)
    .sort((a, b) => b.length - a.length)
    .find((p) => ruta === p || ruta.startsWith(`${p}/`));
  return base ? RUTAS_VISTAS[base] : null;
}
