-- Borradores separados de Plan/Suscripcion: esta migración no cambia contratos ni precios.
CREATE TABLE "PlanBorrador" (
  "id" UUID NOT NULL,
  "codigo" TEXT NOT NULL,
  "orden" INTEGER NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "catalogoVersion" INTEGER NOT NULL DEFAULT 1,
  "contenido" JSONB NOT NULL,
  "creadoEl" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "actualizadoEl" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PlanBorrador_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PlanBorrador_codigo_key" ON "PlanBorrador"("codigo");
INSERT INTO "PlanBorrador" ("id", "codigo", "orden", "contenido") VALUES ('28a37ab4-75af-41e9-8120-9e4056f26000', 'esencial', 0, '{"nombre": "Grafo Esencial", "descripcion": "Cotizá, vendé y organizá tus trabajos.", "usuariosIncluidos": 3, "adicionalesPermitidos": true, "almacenamientoModo": "pendiente", "almacenamientoGb": null, "funciones": {"identidad": true, "roles": true, "empresa": true, "archivos": true, "notificaciones": true, "cuenta": true, "cotizacion": true, "presupuestos": true, "aprobacion_presupuestos": true, "documentos_pdf": true, "ordenes": true, "seguimiento_qr": true, "proyectos": false, "aprobacion_arte": false, "clientes": true, "cupones": false, "fidelizacion": false, "empleados": false, "materiales": true, "productos": true, "productos_compuestos": true, "procesos": true, "centros_costo": true, "maquinaria": true, "reglas_precio": true, "precios_especiales": false, "analisis_vectorial": true, "geometrias": true, "aprovechamiento_cotizacion": true, "exportacion_fabricacion": false, "recorridos_fabricacion": false, "centro_copiado": true, "terminaciones_copiado": true, "cotizacion_cad": true, "impresion_directa": false, "colas_impresion": false, "etiquetas_pdf": true, "tablero": true, "estaciones": true, "equipos_produccion": false, "asignacion_automatica": false, "eta_capacidad": false, "planificacion_avanzada": false, "colas_produccion": false, "existencias": true, "reservas": false, "prevision_materiales": false, "proveedores": true, "compras": false, "recepciones": false, "cobros": true, "cuentas_cobrar": true, "tesoreria": false, "valores": false, "cuentas_pagar": false, "gastos_recurrentes": false, "gastos_fijos": true, "fiscal_argentina": true, "reportes_resumen": true, "reportes_finanzas": false, "reportes_comerciales": false, "reportes_produccion": false, "whatsapp_automatico": false, "whatsapp_web": false, "mcp": false}}'::jsonb);
INSERT INTO "PlanBorrador" ("id", "codigo", "orden", "contenido") VALUES ('28a37ab4-75af-41e9-8120-9e4056f26001', 'pro', 1, '{"nombre": "Grafo Pro", "descripcion": "Conectá ventas, materiales y administración.", "usuariosIncluidos": 20, "adicionalesPermitidos": true, "almacenamientoModo": "pendiente", "almacenamientoGb": null, "funciones": {"identidad": true, "roles": true, "empresa": true, "archivos": true, "notificaciones": true, "cuenta": true, "cotizacion": true, "presupuestos": true, "aprobacion_presupuestos": true, "documentos_pdf": true, "ordenes": true, "seguimiento_qr": true, "proyectos": true, "aprobacion_arte": true, "clientes": true, "cupones": true, "fidelizacion": true, "empleados": true, "materiales": true, "productos": true, "productos_compuestos": true, "procesos": true, "centros_costo": true, "maquinaria": true, "reglas_precio": true, "precios_especiales": true, "analisis_vectorial": true, "geometrias": true, "aprovechamiento_cotizacion": true, "exportacion_fabricacion": false, "recorridos_fabricacion": false, "centro_copiado": true, "terminaciones_copiado": true, "cotizacion_cad": true, "impresion_directa": false, "colas_impresion": false, "etiquetas_pdf": true, "tablero": true, "estaciones": true, "equipos_produccion": true, "asignacion_automatica": false, "eta_capacidad": false, "planificacion_avanzada": false, "colas_produccion": false, "existencias": true, "reservas": true, "prevision_materiales": true, "proveedores": true, "compras": true, "recepciones": true, "cobros": true, "cuentas_cobrar": true, "tesoreria": true, "valores": true, "cuentas_pagar": true, "gastos_recurrentes": true, "gastos_fijos": true, "fiscal_argentina": true, "reportes_resumen": true, "reportes_finanzas": true, "reportes_comerciales": true, "reportes_produccion": false, "whatsapp_automatico": true, "whatsapp_web": true, "mcp": false}}'::jsonb);
INSERT INTO "PlanBorrador" ("id", "codigo", "orden", "contenido") VALUES ('28a37ab4-75af-41e9-8120-9e4056f26002', 'avanzado', 2, '{"nombre": "Grafo Avanzado", "descripcion": "Planificá y optimizá toda tu producción.", "usuariosIncluidos": 40, "adicionalesPermitidos": true, "almacenamientoModo": "pendiente", "almacenamientoGb": null, "funciones": {"identidad": true, "roles": true, "empresa": true, "archivos": true, "notificaciones": true, "cuenta": true, "cotizacion": true, "presupuestos": true, "aprobacion_presupuestos": true, "documentos_pdf": true, "ordenes": true, "seguimiento_qr": true, "proyectos": true, "aprobacion_arte": true, "clientes": true, "cupones": true, "fidelizacion": true, "empleados": true, "materiales": true, "productos": true, "productos_compuestos": true, "procesos": true, "centros_costo": true, "maquinaria": true, "reglas_precio": true, "precios_especiales": true, "analisis_vectorial": true, "geometrias": true, "aprovechamiento_cotizacion": true, "exportacion_fabricacion": false, "recorridos_fabricacion": false, "centro_copiado": true, "terminaciones_copiado": true, "cotizacion_cad": true, "impresion_directa": false, "colas_impresion": false, "etiquetas_pdf": true, "tablero": true, "estaciones": true, "equipos_produccion": true, "asignacion_automatica": true, "eta_capacidad": true, "planificacion_avanzada": true, "colas_produccion": true, "existencias": true, "reservas": true, "prevision_materiales": true, "proveedores": true, "compras": true, "recepciones": true, "cobros": true, "cuentas_cobrar": true, "tesoreria": true, "valores": true, "cuentas_pagar": true, "gastos_recurrentes": true, "gastos_fijos": true, "fiscal_argentina": true, "reportes_resumen": true, "reportes_finanzas": true, "reportes_comerciales": true, "reportes_produccion": true, "whatsapp_automatico": true, "whatsapp_web": true, "mcp": false}}'::jsonb);
