import type { Project, StyleId, Parameters, JointParameters } from "./types";
import { DEFAULT_LIGHTBOX, LIGHTBOX_LAYERS } from "./lightbox";
export const STYLES: {
  id: StyleId;
  name: string;
  short: string;
  description: string;
  family: string;
}[] = [
  {
    id: "solid-back",
    name: "Frente acrílico",
    short: "Fondo impreso",
    description: "Cuerpo cerrado con apoyo para un frente de acrílico.",
    family: "Acrílico",
  },
  {
    id: "open-back",
    name: "Fondo abierto",
    short: "Liviana y accesible",
    description: "Perfil abierto con frente apoyado sobre el borde superior.",
    family: "Acrílico",
  },
  {
    id: "double-support",
    name: "Doble apoyo",
    short: "Frente y fondo",
    description: "Apoyos independientes para cerrar ambas caras.",
    family: "Acrílico",
  },
  {
    id: "single-support",
    name: "Apoyo único",
    short: "Perfil esencial",
    description: "Un perfil con asiento interior para el frente.",
    family: "Acrílico",
  },
  {
    id: "back-fit",
    name: "Encastre trasero",
    short: "Acceso de servicio",
    description: "Borde frontal y paredes escalonadas para fondo de PVC.",
    family: "Acrílico",
  },
  {
    id: "halo",
    name: "Retroiluminada",
    short: "Luz hacia la pared",
    description: "Cara impresa y cuerpo abierto para iluminación posterior.",
    family: "Iluminación",
  },
  {
    id: "acrylic-fit",
    name: "Acrílico encastrable",
    short: "Frente desmontable",
    description: "Frente alojado en una ranura interior con holgura ajustable.",
    family: "Encastre",
  },
  {
    id: "printed-fit",
    name: "Frente impreso",
    short: "Dos piezas impresas",
    description: "Cuerpo y tapa impresa con reborde de encastre.",
    family: "Encastre",
  },
  {
    id: "double-led",
    name: "Doble iluminación",
    short: "Frente + halo",
    description: "Separación interna para luz frontal y posterior.",
    family: "Iluminación",
  },
  {
    id: "perforated",
    name: "Frente calado",
    short: "Difusor acrílico",
    description:
      "Frente impreso con seis patrones de calado, difusor acrílico interno y base desmontable.",
    family: "Iluminación",
  },
  {
    id: "curved",
    name: "Letra curva",
    short: "Barrido angular y base",
    description: "Letra extruida por un arco, con base unida o desmontable.",
    family: "Especial",
  },
  {
    id: "neon",
    name: "Canal neón",
    short: "Tira LED flexible",
    description:
      "Canal perimetral sobre una base con ancho de tira configurable.",
    family: "Iluminación",
  },
  {
    id: "organic",
    name: "Orgánica",
    short: "Siete perfiles de pared",
    description: "Zigzag, barriga, pedestal, ondas, bumper, bubble y frisos.",
    family: "Especial",
  },
];
export const TRAY_STYLES: StyleId[] = [
  "solid-back",
  "open-back",
  "single-support",
  "back-fit",
  "acrylic-fit",
  "printed-fit",
];
export const DEFAULT_PARAMS: Parameters = {
  base: 2,
  wall: 2,
  innerWall: 2,
  height: 35,
  acrylic: 3.1,
  clearance: 0.15,
  ledge: 1,
  lip: 5,
  lipEnabled: false,
  lipHeight: 2,
  mirror: false,
  doubleHalo: false,
  gap: 2,
  outerHeight: 40,
  backTray: false,
  trayWall: 4,
  traySheet: 1.2,
  retention: 0.6,
  liner: false,
  curve: 8, // Compatibilidad de proyectos anteriores; reemplazado por el barrido angular.
  neonWidth: 10,
  corner: "Miter",
  pvc: 3,
  cutClearance: 0.1,
  supportAngle: 30,
  flatSupport: false,
  borderWidth: 2,
  borderThickness: 1,
  outerRecess: 0,
  innerReduction: 20,
  fitBaseHeight: 0, // 0 conserva la altura derivada de los proyectos anteriores.
  fitBaseType: "legacy",
  fitRimWall: 1.5,
  fitRimHeight: 3,
  fitRingWidth: 2,
  fitChannelGap: 5.8,
  fitChannelHeight: 12,
  fitChannelFloor: 2,
  fitLockDepth: 2,
  fitLockHeight: 2,
  fitLockOffset: 0,
  fitWallProfile: "straight",
  fitProfileDirection: "outward",
  fitProfileAngle: 5,
  fitProfileTop: 3,
  fitProfileBottom: 3,
  patternType: "circle",
  patternSize: 3,
  patternLength: 6,
  patternSpacing: 1.5,
  patternBorder: 4,
  patternMargin: 0,
  patternRotation: 0,
  patternAngle: 0,
  secondInnerWall: 2,
  cornerRadius: 1.5,
  trayDepth: 2,
  curveAngle: 60,
  curveRadius: 60,
  curveCenter: 120,
  curveSegments: 128,
  curveBase: true,
  curveBaseThickness: 10,
  curveSide: 20,
  curveDepth: 15,
  curveAdvance: 0,
  curveBaseRadius: 5,
  curveSeparate: false,
  curveFitDepth: 8,
  curveFitClearance: 0.2,
  neonOutline: false,
  neonPosition: 5,
  neonRetention: 0.8,
  neonRetentionHeight: 1.5,
  organicProfile: "zigzag",
  organicAmplitude: 3,
  organicPeriod: 10,
  organicBelly: 5,
  organicExpansion: 6,
  organicCurvature: 60,
  organicWaveAmplitude: 2,
  organicWavePeriod: 8,
  organicWaveShape: 50,
  organicBumper: 5,
  organicFoot: 8,
  organicCloseBase: true,
  organicBubble: 50,
  organicRadius: 10,
  organicCount: 2,
  organicStackAdvance: 1.5,
  organicStackGap: 2,
  organicSlant: 0,
  organicAngle: 45,
  organicSolid: false,
  organicFace: "acrylic",
  organicBack: "printed",
  organicFit: "front",
  organicFaceAdvance: 0,
  organicFaceCorner: "straight",
  organicFaceRadius: 1,
  organicShell: false,
  organicShellThickness: 1.6,
  pvcClearance: 0.15,
  organicCapSheet: 1.2,
  organicCapHeight: 8,
  organicCapWall: 1.6,
  organicCapClearance: 0.15,
  organicPvcSupport: true,
  pinDiameter: 10,
  pinHeight: 0,
  pinHole: 0,
};
export const DEFAULT_JOINT: JointParameters = {
  ball: 15,
  clearance: 0.4,
  retention: 0.7,
  chamfer: 1.8,
  flangeLength: 40,
  flangeWidth: 26.5,
  flangeHeight: 4,
  flangeRadius: 8,
  screw: 4.2,
  screwSpacing: 29.5,
  recess: 8,
  recessDepth: 2,
  centralHole: 4.2,
  notches: true,
  notch: 5,
  baseDiameter: 18,
  baseHeight: 5,
  neck: 10,
  neckHeight: 2.4,
  fillet: 1.2,
  flatTop: 11,
  tipDiameter: 8,
  tipAngle: 90,
  socketHeight: 25,
  socketTop: 26,
  socketBottom: 22,
  socketScrew: 5,
  countersink: 9,
  socketFlange: 32,
  socketFlangeHeight: 2,
  slots: 4,
  slotWidth: 2.6,
  slotLength: 19,
  fingerThin: 2.2,
  rootRelief: true,
  tilt: 0,
};
export function newProject(): Project {
  return {
    version: 1,
    mode: "letters",
    id: crypto.randomUUID(),
    name: "Letras GRAFO",
    source: {
      mode: "text",
      text: "GRAFO",
      font: "BebasNeue",
      height: 100,
      spacing: 4,
      svg: "",
      fileName: "",
    },
    style: "solid-back",
    params: { ...DEFAULT_PARAMS },
    features: [],
    cuts: [],
    joint: { ...DEFAULT_JOINT },
    lightbox: { ...DEFAULT_LIGHTBOX },
    faceArtwork: { a: "", b: "" },
    production: {
      bedWidth: 220,
      bedHeight: 220,
      bedDepth: 250,
      gap: 5,
      rotate: true,
      filament: "PLA",
      density: 1.24,
      priceKg: 22000,
      gramsHour: 12,
      machineHour: 1800,
      acrylicM2: 45000,
      pvcM2: 25000,
      flexiblePriceKg: 30000,
      flexibleDensity: 1.2,
      waste: 10,
      margin: 35,
      currency: "ARS",
      company: "Mi taller",
      contact: "",
      logo: "",
      checklist:
        "Revisar medidas\nLaminar y verificar tiempos\nProbar encastres\nMontar iluminación\nControl final",
    },
    colors: {
      body: "#26323d",
      face: "#fff0e5",
      back: "#b6c0ca",
      pvc: "#d7dbe0",
      liner: "#fafafa",
      pin: "#fd6900",
      socket: "#64788c",
      boxBody: "#26323d", faceA: "#fff9ee", faceB: "#fff9ee",
      rimA: "#26323d", rimB: "#26323d", clips: "#64788c", keys: "#fd6900",
      lightRails: "#dce3e7", wallMount: "#26323d", seals: "#626b72",
    },
    hidden: [],
    updatedAt: new Date().toISOString(),
  };
}
export function styleDefaults(id: StyleId): Parameters {
  const d = { ...DEFAULT_PARAMS };
  const specific: Partial<Record<StyleId, Partial<Parameters>>> = {
    "double-support": { height: 45, acrylic: 3 },
    "single-support": { height: 45, acrylic: 3 },
    "back-fit": { mirror: true, borderWidth: 0.5, pvc: 10 },
    halo: { mirror: true, wall: 4, innerWall: 3, height: 50, corner: "Round" },
    "acrylic-fit": { mirror: true, height: 45, clearance: 0.1, traySheet: 1 },
    "printed-fit": { mirror: true, height: 45, clearance: 0.1, traySheet: 1 },
    perforated: {
      mirror: true,
      height: 40,
      base: 1.2,
      acrylic: 2,
      fitBaseType: "flush",
      fitBaseHeight: 20,
      traySheet: 1.5,
      clearance: 0.2,
      fitProfileTop: 4,
    },
    "double-led": { gap: 10 },
    neon: { height: 7, base: 1.2, wall: 1.2 },
    organic: {
      height: 30,
      acrylic: 3,
      supportAngle: 45,
      pvc: 10,
      borderThickness: 2,
    },
  };
  return { ...d, ...specific[id] };
}
export function chooseStyle(p: Project, id: StyleId): Project {
  if (p.mode === "letters" && p.style === id) return p;
  return {
    ...p,
    mode: "letters",
    style: id,
    params: p.styleParameters?.[id]
      ? { ...styleDefaults(id), ...p.styleParameters[id] }
      : styleDefaults(id),
    styleParameters: { ...p.styleParameters, [p.style]: { ...p.params } },
    features: [],
    cuts: [],
  };
}
export const LAYER_NAMES = {
  ...LIGHTBOX_LAYERS,
  clips: "Presillas del cierre anterior",
  lightRails: "Soportes LED anteriores",
  body: "Cuerpo",
  face: "Frente",
  back: "Fondo",
  pvc: "Fondo PVC",
  liner: "Revestimiento",
  pin: "Perno",
  socket: "Alojamiento",
};
