/** Catálogo comercial propuesto. No sustituye los derechos efectivos de las suscripciones. */
export const VERSION_CATALOGO_PLANES = 2;
export type CapacidadPlan = {
  id: string;
  clave: string;
  grupo: string;
  nombre: string;
  descripcion: string;
  nota: string;
  base: boolean;
  destino: 'plan' | 'piloto' | 'adicional';
  cobertura: 'base' | 'implementada' | 'parcial' | 'pendiente';
  revisionOperativa: boolean;
  requiere: string[];
  complementos: string[];
};
export const GRUPOS_PLANES: Record<string, string> = {
  B: 'Cuenta y seguridad',
  C: 'Venta y órdenes',
  R: 'Clientes y equipo',
  T: 'Catálogo y costos',
  G: 'Geometría y fabricación',
  I: 'Copiado e impresión',
  P: 'Producción y planificación',
  S: 'Stock y compras',
  F: 'Administración',
  A: 'Reportes',
  X: 'Integraciones',
};

export const CATALOGO_PLANES: CapacidadPlan[] = [
  {
    id: 'B01',
    clave: 'identidad',
    grupo: 'B',
    nombre: 'Identidad, perfil y MFA',
    descripcion:
      'Identidad, login, contraseña, perfil, foto, MFA, recuperación y sesiones',
    nota: 'Base técnica; seguridad disponible en todos los planes',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B02',
    clave: 'roles',
    grupo: 'B',
    nombre: 'Usuarios, roles y permisos',
    descripcion:
      'Aislamiento de empresa, pertenencias, roles, permisos y restricciones de acceso',
    nota: 'Base técnica; el plan nunca concede un permiso personal',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B03',
    clave: 'empresa',
    grupo: 'B',
    nombre: 'Empresa y marca',
    descripcion: 'Datos y marca de la empresa, país y configuración general',
    nota: 'Base técnica; requisitos fiscales y regionales separados de la oferta',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B04',
    clave: 'archivos',
    grupo: 'B',
    nombre: 'Archivos y versiones',
    descripcion: 'Archivos, versiones, descarga, papelera y restauración',
    nota: 'Base compartida con cupo independiente; política de conservación explícita',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B05',
    clave: 'notificaciones',
    grupo: 'B',
    nombre: 'Notificaciones internas',
    descripcion: 'Notificaciones internas, eventos y resumen de actividad',
    nota: 'Base compartida; no confundir con mensajería externa paga',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B06',
    clave: 'cuenta',
    grupo: 'B',
    nombre: 'Cuenta y suscripción',
    descripcion:
      'Alta, suscripción, medios de gestión del cobro SaaS y acceso a soporte',
    nota: 'Base técnica; Backoffice y Paddle son operación de Grafo',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'C01',
    clave: 'cotizacion',
    grupo: 'C',
    nombre: 'Cotizador completo',
    descripcion: 'Cotización, varios ítems, cálculo y recotización',
    nota: 'Catálogo y costos T01–T05. Control en cálculo, recotización, persistencia y cola; S03 sigue siendo opcional para cotizar.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [
      'materiales',
      'productos',
      'procesos',
      'centros_costo',
      'reglas_precio',
    ],
    complementos: ['prevision_materiales'],
  },
  {
    id: 'C02',
    clave: 'presupuestos',
    grupo: 'C',
    nombre: 'Presupuestos',
    descripcion: 'Presupuestos, emisión, respuesta comercial y conversión a OT',
    nota: 'Emisión propia; enlace público y PDF son complementos. Históricos consultables y resolubles al retirar el módulo; convertir exige C05.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cotizacion', 'clientes'],
    complementos: [],
  },
  {
    id: 'C03',
    clave: 'aprobacion_presupuestos',
    grupo: 'C',
    nombre: 'Aprobación pública de presupuestos',
    descripcion: 'Presupuesto público y aprobación del cliente',
    nota: 'Se controla la emisión y reactivación del enlace. Los tokens vigentes conservan consulta y decisión, respetando caducidad y revocación.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['presupuestos'],
    complementos: [],
  },
  {
    id: 'C04',
    clave: 'documentos_pdf',
    grupo: 'C',
    nombre: 'Documentos PDF',
    descripcion: 'Documentos PDF del negocio',
    nota: 'Generación/reintento controlados en presupuesto, recibo, factura, estado de cuenta y worker. Descargas ya guardadas conservadas; etiquetas I06 tienen cierre separado.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'C05',
    clave: 'ordenes',
    grupo: 'C',
    nombre: 'Órdenes y entrega',
    descripcion:
      'Órdenes, ítems, emisión, modificaciones, cancelación y entrega',
    nota: 'Se controlan altas, emisión de borradores y cambios de productos. Permite terminar, cobrar y entregar OTs emitidas; no exige seguimiento ni impresión.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cotizacion', 'clientes'],
    complementos: [],
  },
  {
    id: 'C06',
    clave: 'seguimiento_qr',
    grupo: 'C',
    nombre: 'Seguimiento y QR',
    descripcion: 'Seguimiento público, identificación QR y entrega por escaneo',
    nota: 'Se controla la creación de seguimiento público. Los enlaces previos y el escaneo del número de una OT emitida conservan continuidad; revisar generación de etiquetas con I06.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'C07',
    clave: 'proyectos',
    grupo: 'C',
    nombre: 'Campañas y proyectos',
    descripcion:
      'Campañas/proyectos: equipo, hitos y agrupación de presupuestos y OT',
    nota: 'Control en rutas de campañas y vinculación al crear presupuestos/OT; navegación y selector condicionados. Las campañas previas conservan consulta y cierre; los compromisos abiertos se revisan antes de retirar la función.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['presupuestos', 'ordenes'],
    complementos: [],
  },
  {
    id: 'C08',
    clave: 'aprobacion_arte',
    grupo: 'C',
    nombre: 'Aprobación de arte y revisiones',
    descripcion:
      'Desarrollo documental, revisiones de arte, solicitudes, aprobación y liberación',
    nota: 'Arte y revisiones en OT independientes o campañas. Las escrituras revalidan el contrato; solicitudes pendientes y producción bloqueada impiden retirar la función. Conserva historial y permite cancelar, revocar enlaces y retirar controles. Ver recorrido C08 y límites en la documentación de planes.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes', 'archivos'],
    complementos: [],
  },
  {
    id: 'R01',
    clave: 'clientes',
    grupo: 'R',
    nombre: 'Clientes y contactos',
    descripcion: 'Clientes, contactos, importación y consulta de su actividad',
    nota: 'Alta, importación, edición y bajas controladas en API/UI. Se conservan consulta, selección y uso de clientes existentes; el escaneo no ejecuta un alta si R01 está excluida.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'R02',
    clave: 'cupones',
    grupo: 'R',
    nombre: 'Cupones',
    descripcion: 'Cupones, validación y uso',
    nota: 'Crear, editar, reservar y redimir revalidan contrato y cambios pendientes bajo lock. El diagnóstico impide retirar Cupones con reservas, conversiones parciales u OT abiertas con descuentos. Concluidos esos compromisos, conserva consulta e historial sin nuevas aplicaciones. Verificado con contratos publicados y emisión directa o desde borrador.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cotizacion'],
    complementos: [],
  },
  {
    id: 'R03',
    clave: 'fidelizacion',
    grupo: 'R',
    nombre: 'Fidelización',
    descripcion: 'Fidelización, configuración, ajustes y simulación',
    nota: 'Escrituras y compromisos revalidados bajo lock. El diagnóstico exige cerrar canjes y puntos prometidos antes de retirar la función. Conserva saldos, historial y correcciones de acreditaciones previas, sin nuevas ganancias ni canjes. Probado con contratos publicados y reservas concurrentes.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['clientes'],
    complementos: [],
  },
  {
    id: 'R04',
    clave: 'empleados',
    grupo: 'R',
    nombre: 'Registro de empleados',
    descripcion:
      'Empleados, vinculación a usuarios, capacidades y remuneraciones',
    nota: 'Edición, importación y bajas del legajo controladas; consulta y referencias de costos conservadas. El acceso de usuario y su revocación siguen siendo base.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T01',
    clave: 'materiales',
    grupo: 'T',
    nombre: 'Materiales, variantes y costos',
    descripcion:
      'Materiales, variantes, unidades, presentaciones, costos y biblioteca',
    nota: 'Configuración de materiales, variantes, costos y biblioteca controlada. Las lecturas del motor no requieren gestión de stock S01.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T02',
    clave: 'productos',
    grupo: 'T',
    nombre: 'Productos y formularios',
    descripcion: 'Productos, formularios y configuración comercial',
    nota: 'Altas, cambios, duplicación y bajas controlados; fichas en consulta al retirar edición. Cotizaciones e historial conservan sus referencias.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'T03',
    clave: 'productos_compuestos',
    grupo: 'T',
    nombre: 'Productos compuestos y recetas',
    descripcion: 'Recetas, componentes, revisiones y publicación del producto',
    nota: 'Crear, convertir o copiar compuestos y modificar sus recetas exige T03. Las rutas simples y sus revisiones usan T02/T04; las versiones internas se conservan al cotizar.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['productos', 'procesos'],
    complementos: [],
  },
  {
    id: 'T04',
    clave: 'procesos',
    grupo: 'T',
    nombre: 'Procesos y flujos',
    descripcion:
      'Procesos reutilizables, familias, flujos y alternativas de producción',
    nota: 'Edición de pasos y flujos controlada. Configurar rutas de productos requiere T02/T04; lectura y ejecución de trabajos existentes preservadas.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'T05',
    clave: 'centros_costo',
    grupo: 'T',
    nombre: 'Centros de costo y tarifas',
    descripcion: 'Centros de costo, tarifas, capacidades e historial',
    nota: 'Configuración de centros, planillas y publicación de tarifas controlada. El cálculo consume tarifas guardadas sin abrir su editor.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T06',
    clave: 'maquinaria',
    grupo: 'T',
    nombre: 'Maquinaria y consumos',
    descripcion: 'Maquinaria, perfiles, consumos e historial',
    nota: 'Alta, edición, activación y baja de maquinaria controladas. Sus perfiles y consumos siguen disponibles al motor. Es independiente de una impresora conectada I04.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['centros_costo'],
    complementos: [],
  },
  {
    id: 'T07',
    clave: 'reglas_precio',
    grupo: 'T',
    nombre: 'Precios, impuestos y monedas',
    descripcion:
      'Cargos, impuestos, comisiones, reglas de precio y tipos de cambio',
    nota: 'Reglas de precio, cargos, impuestos, comisiones y configuración de cambio controlados. Se preservan su lectura y las tasas de cada cotización.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T08',
    clave: 'precios_especiales',
    grupo: 'T',
    nombre: 'Precios especiales por cliente',
    descripcion: 'Precios especiales por cliente/producto',
    nota: 'Gestión y aplicación de precios por cliente controladas. Las escrituras y el motor revalidan el contrato al guardar. Retirar T08 conserva reglas en consulta e importes guardados; las nuevas cotizaciones y recotizaciones usan el precio general. T08 se configura independientemente de T07.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['clientes', 'productos'],
    complementos: [],
  },
  {
    id: 'G01',
    clave: 'analisis_vectorial',
    grupo: 'G',
    nombre: 'Medición y análisis vectorial',
    descripcion: 'Análisis y preparación vectorial, medidas y geometrías',
    nota: 'Entradas HTTP de análisis y preparación protegidas. La cotización conserva las primitivas geométricas internas; las fuentes explícitas exigen capacidad incluso por cola.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'G02',
    clave: 'geometrias',
    grupo: 'G',
    nombre: 'Geometrías del producto',
    descripcion: 'Geometrías del producto e interpretación por lotes',
    nota: 'Interpretación por lotes y cambios de geometría del catálogo protegidos. Se conservan los diseños ya configurados; requiere G01 y productos.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['analisis_vectorial', 'productos'],
    complementos: [],
  },
  {
    id: 'G03',
    clave: 'aprovechamiento_cotizacion',
    grupo: 'G',
    nombre: 'Nesting rectangular en rollos y placas',
    descripcion:
      'Acomodo rectangular de piezas para calcular el aprovechamiento en rollos, placas y pliegos',
    nota: 'Base del aprovechamiento por medidas. El acomodo por contornos exige además G06; las cotizaciones por medidas y las estimaciones manuales siguen disponibles sin esa función.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['analisis_vectorial', 'materiales'],
    complementos: [],
  },
  {
    id: 'G06',
    clave: 'nesting_irregular',
    grupo: 'G',
    nombre: 'Nesting irregular',
    descripcion: 'Optimización por contornos de piezas vectoriales sobre placas, incluidas letras y formas irregulares',
    nota: 'Control independiente del nesting rectangular. Se exige antes de calcular o reutilizar un acomodo irregular y se revalida en los workers. Los resultados históricos se conservan.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['aprovechamiento_cotizacion'],
    complementos: [],
  },
  {
    id: 'G04',
    clave: 'exportacion_fabricacion',
    grupo: 'G',
    nombre: 'Exportación de fabricación DXF',
    descripcion: 'Exportación de fabricación y capas DXF',
    nota: 'Capas y exportación en API, descargas del visor y consultas auxiliares controladas. La geometría necesaria para cotizar permanece disponible.',
    base: false,
    destino: 'adicional',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['geometrias'],
    complementos: [],
  },
  {
    id: 'G05',
    clave: 'recorridos_fabricacion',
    grupo: 'G',
    nombre: 'Recorridos y plantillas de fabricación',
    descripcion: 'Recorridos, revisiones y archivos de fabricación/plantillas',
    nota: 'Nuevas revisiones, regeneración y plantillas protegidas. Consulta y descarga de revisiones guardadas y cierre de estados previos conservados con permisos personales.',
    base: false,
    destino: 'adicional',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['geometrias'],
    complementos: [],
  },
  {
    id: 'I01',
    clave: 'centro_copiado',
    grupo: 'I',
    nombre: 'Centro de copiado: documentos',
    descripcion:
      'Cotización de documentos: PDF, páginas/rangos, copias, orientación, color, faz y papel',
    nota: 'Cotizar y guardar no exige impresión conectada. El motor revalida el contrato bajo lock al guardar o recotizar, también si se omite la metadata de la plantilla.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cotizacion', 'archivos'],
    complementos: [],
  },
  {
    id: 'I02',
    clave: 'terminaciones_copiado',
    grupo: 'I',
    nombre: 'Terminaciones y tomos',
    descripcion: 'Terminaciones, agrupación y tomos',
    nota: 'Control propio en cargas, tomos y configuración. El guardado del tomo revalida el contrato en su transacción; retirar la función conserva los históricos.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['centro_copiado'],
    complementos: [],
  },
  {
    id: 'I03',
    clave: 'cotizacion_cad',
    grupo: 'I',
    nombre: 'Cotización de planos CAD',
    descripcion:
      'Cotización CAD por rollo, tamaños grandes y configuración por página',
    nota: 'CAD cotizado y emitido en OT con Esencial, Pro y Avanzado publicados, sin impresión conectada. Rangos y copias por página conservados; retirar CAD durante el cálculo impide guardar.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['centro_copiado', 'materiales'],
    complementos: [],
  },
  {
    id: 'I04',
    clave: 'impresion_directa',
    grupo: 'I',
    nombre: 'Impresión conectada',
    descripcion:
      'Impresión directa: conexión QZ, impresoras, bandejas y perfiles',
    nota: 'Control por impresion_directa para conexión, perfiles, pruebas y etiquetas. Los documentos de OT requieren también colas_impresion y revalidan el contrato dentro de la transacción antes de generar la firma.',
    base: false,
    destino: 'piloto',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'I05',
    clave: 'colas_impresion',
    grupo: 'I',
    nombre: 'Asistente y colas de impresión',
    descripcion:
      'Asistente, colas por máquina, preparación del operario, envíos y confirmaciones',
    nota: 'Encolar, preparar y liberar lotes revalidan el contrato bajo lock, incluido un cambio pendiente que retire impresión. El diagnóstico distingue solicitudes sin envío y salidas sin verificar, con aceptación explícita y revisión de cambios. La OT conserva historial y verificación humana sin cargar QZ.',
    base: false,
    destino: 'piloto',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['impresion_directa'],
    complementos: [],
  },
  {
    id: 'I06',
    clave: 'etiquetas_pdf',
    grupo: 'I',
    nombre: 'Etiquetas descargables',
    descripcion: 'Etiquetas QR y descarga para impresión manual',
    nota: 'La descarga PDF se valida en el servidor con I06; la vista previa admite I06 o impresión directa. No necesita QZ ni seguimiento público.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'P01',
    clave: 'tablero',
    grupo: 'P',
    nombre: 'Tablero y tareas',
    descripcion: 'Tablero, lista, tareas, tramos y progreso del trabajo',
    nota: 'La emisión fija si la OT usa tareas. Sin P01 no se materializan pasos ni se incorporan órdenes nuevas al tablero; el recorrido manual confirma preparación al entregar. Las OT anteriores conservan ejecución.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes', 'procesos'],
    complementos: [],
  },
  {
    id: 'P02',
    clave: 'estaciones',
    grupo: 'P',
    nombre: 'Estaciones y calendarios',
    descripcion: 'Estaciones, recursos, calendarios y disponibilidad',
    nota: 'Altas, cambios y bajas de estaciones, calendarios y configuración protegidos por P02 y permiso personal. Se conserva consulta y uso de recursos históricos.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['centros_costo'],
    complementos: [],
  },
  {
    id: 'P03',
    clave: 'equipos_produccion',
    grupo: 'P',
    nombre: 'Equipos productivos',
    descripcion: 'Equipos productivos y capacidades',
    nota: 'Alta/edición de equipos y cambios de personal u horarios desde estaciones controlados. Se conserva la configuración histórica. Empleados sin login no equivalen a licencias.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['empleados', 'estaciones'],
    complementos: [],
  },
  {
    id: 'P04',
    clave: 'asignacion_automatica',
    grupo: 'P',
    nombre: 'Asignación automática de personal',
    descripcion:
      'Asignación de personal: simulación, confirmación y reconciliación',
    nota: 'Asignación independiente de ETA: lectura, simulación, confirmación y scheduler verifican P04. Las escrituras revalidan el contrato bajo lock y se detienen ante una contratación que retira la función. Se conservan responsables y ejecución de tareas previas; el diagnóstico exige revisar las asignaciones abiertas. Verificado con contratos publicados.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['tablero', 'equipos_produccion'],
    complementos: [],
  },
  {
    id: 'P05',
    clave: 'eta_capacidad',
    grupo: 'P',
    nombre: 'Estimación según capacidad',
    descripcion: 'ETA, contexto y estimaciones de capacidad/entrega',
    nota: 'Promesas y snapshots revalidan el contrato al guardar, incluso durante cambios pendientes. La consulta del contexto no modifica pasos. El cierre de OT conserva tiempos reales y promesas previas sin exigir ETA; su análisis admite ETA o Reportes de producción. Cotizador y tablero conservan la fecha manual.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['tablero', 'estaciones'],
    complementos: ['prevision_materiales'],
  },
  {
    id: 'P06',
    clave: 'planificacion_avanzada',
    grupo: 'P',
    nombre: 'Escenarios y reprogramación',
    descripcion: 'Escenarios de planificación, elección y reprogramación',
    nota: 'Contrato revalidado dentro de solicitudes, selección, reprogramación y materialización; el worker verifica antes de calcular y publicar. Consulta histórica conservada. Falta completar recorridos de lotes abiertos y navegador.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['eta_capacidad'],
    complementos: [],
  },
  {
    id: 'P07',
    clave: 'colas_produccion',
    grupo: 'P',
    nombre: 'Optimización de colas productivas',
    descripcion: 'Colas productivas, agrupación y acciones sobre trabajos',
    nota: 'Consultas, simulación y acciones de cola verifican el contrato también en servicios internos. La ejecución revalida bajo lock de empresa y la simulación antes de entregar el resultado. Al retirar la función, las OT conservan ejecución e historial desde el tablero. Verificado con versiones publicadas; no crea tandas productivas persistidas.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['tablero'],
    complementos: [],
  },
  {
    id: 'S01',
    clave: 'existencias',
    grupo: 'S',
    nombre: 'Existencias y movimientos',
    descripcion:
      'Almacenes, ubicaciones, existencias, transferencias y movimientos',
    nota: 'Mutaciones públicas de depósitos, ubicaciones, movimientos y transferencias controladas. Se conservan costos e historial; reservas previas admiten consumo/liberación. Las compras y reservas abiertas se incluyen en el diagnóstico de cambio de plan.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'S02',
    clave: 'reservas',
    grupo: 'S',
    nombre: 'Reservas automáticas por OT',
    descripcion: 'Reservas de materiales por OT y consumo',
    nota: 'Emisión, comandos y política coordinados con cambios de contrato. Probadas emisión directa y desde borrador, consumo/liberación y concurrencia entre conexiones. Sin la función, una OT nueva no genera reservas.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['existencias', 'ordenes'],
    complementos: [],
  },
  {
    id: 'S03',
    clave: 'prevision_materiales',
    grupo: 'S',
    nombre: 'Previsión de faltantes',
    descripcion: 'Previsión de materiales durante cotización',
    nota: 'Consulta de existencias y reposición independiente de las reservas automáticas; probada con versiones publicadas sin Reservas. Retirarla no bloquea necesidades que conservan su gestión de stock. Falta ampliar recorridos comerciales de navegador.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['existencias', 'cotizacion'],
    complementos: [],
  },
  {
    id: 'S04',
    clave: 'proveedores',
    grupo: 'S',
    nombre: 'Proveedores y reposición',
    descripcion: 'Proveedores, ofertas/costos y plazos de reposición',
    nota: 'T01; registro de proveedor reutilizable en egresos y compras',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'S05',
    clave: 'compras',
    grupo: 'S',
    nombre: 'Compras y abastecimiento',
    descripcion:
      'Necesidades de abastecimiento, borradores y pedidos de compra',
    nota: 'S04/T01; conectar S02 cuando una necesidad proviene de una OT',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['proveedores'],
    complementos: [],
  },
  {
    id: 'S06',
    clave: 'recepciones',
    grupo: 'S',
    nombre: 'Recepciones de materiales',
    descripcion:
      'Recepciones y actualización de stock, incluidas recepciones parciales',
    nota: 'S05/S01; conservar trazabilidad de operaciones iniciadas ante cambios de plan',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['existencias', 'compras'],
    complementos: [],
  },
  {
    id: 'F01',
    clave: 'cobros',
    grupo: 'F',
    nombre: 'Cobros, señas y recibos',
    descripcion: 'Cobros, señas, imputaciones, métodos de pago y recibos',
    nota: 'Métodos y cobros nuevos protegidos. Se conserva cancelar el saldo de OT habilitadas al emitir, con verificación transaccional del importe; los recibos, acreditaciones y reversos existentes mantienen continuidad.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['clientes'],
    complementos: [],
  },
  {
    id: 'F02',
    clave: 'cuentas_cobrar',
    grupo: 'F',
    nombre: 'Saldos y cuentas por cobrar',
    descripcion: 'Cuentas por cobrar, deudores y estado de cuenta',
    nota: 'Extracto y deudores protegidos en API, páginas y navegación. Cobrar una OT o registrar un pago de cliente no consulta el extracto si F02 está excluida.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cobros'],
    complementos: [],
  },
  {
    id: 'F03',
    clave: 'tesoreria',
    grupo: 'F',
    nombre: 'Tesorería y conciliación',
    descripcion:
      'Tesorería, cuentas, movimientos, transferencias, arqueos y conciliación',
    nota: 'Gestión bajo el contrato vigente. Al retirar la función se conservan cuentas y extractos; consultar no acredita cobros. Probado con asignación Pro → Esencial.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cobros'],
    complementos: [],
  },
  {
    id: 'F04',
    clave: 'valores',
    grupo: 'F',
    nombre: 'Valores y cheques',
    descripcion:
      'Valores y cheques: depósito, acreditación, rechazo y reversión',
    nota: 'Requiere Tesorería para operar. Conserva consulta de valores y eventos al retirar gestión; endoso y propios exigen también CxP. Probado con contrato asignado.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['tesoreria'],
    complementos: [],
  },
  {
    id: 'F05',
    clave: 'cuentas_pagar',
    grupo: 'F',
    nombre: 'Egresos y cuentas por pagar',
    descripcion: 'Egresos, cuentas por pagar y órdenes de pago',
    nota: 'Egresos, pagos y categorías conservan consulta al retirar gestión; escrituras revalidadas bajo lock. PDF de orden de pago exige Documentos PDF. Probado con asignación Pro → Esencial.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['proveedores'],
    complementos: [],
  },
  {
    id: 'F06',
    clave: 'gastos_recurrentes',
    grupo: 'F',
    nombre: 'Gastos recurrentes',
    descripcion: 'Gastos recurrentes y generación programada',
    nota: 'Alta y generación revalidadas bajo lock, con continuidad frente a cambios pendientes. Las plantillas previas siguen consultables al retirar la función.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cuentas_pagar'],
    complementos: [],
  },
  {
    id: 'F07',
    clave: 'gastos_fijos',
    grupo: 'F',
    nombre: 'Gastos fijos y costos',
    descripcion: 'Gastos fijos y estructura de costos',
    nota: 'T05/R04; no retirar los insumos necesarios del cálculo básico por una decisión de packaging',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['centros_costo'],
    complementos: [],
  },
  {
    id: 'F08',
    clave: 'fiscal_argentina',
    grupo: 'F',
    nombre: 'Comprobantes y ARCA (Argentina)',
    descripcion: 'Comprobantes, notas y facturación electrónica argentina',
    nota: 'Integración, configuración, borradores y emisiones usan la función individual. Admisión persistida, reserva de numeración y recuperación de resultados sin reenvío. El historial, consultas pendientes y CAE manual conservan continuidad al retirar la función. Nuevas notas requieren ARCA. Emisión y recuperación verificadas en homologación; interfaz revisada con respuestas simuladas.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'A01',
    clave: 'reportes_resumen',
    grupo: 'A',
    nombre: 'Resumen comercial y operativo',
    descripcion: 'Resumen, evolución comercial y embudo',
    nota: 'Resumen, comercial y embudo verificados con los tres contratos publicados. El resumen exige reportes.ver y reportes.ver_resumen; su lectura agregada es propia de A01. Los enlaces a análisis detallados respetan A02/A03 y permisos. Funciona sin módulos opcionales de gestión.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'A02',
    clave: 'reportes_finanzas',
    grupo: 'A',
    nombre: 'Análisis financiero y márgenes',
    descripcion: 'Análisis financiero y márgenes',
    nota: 'Exige A02, reportes.ver y finanzas.ver_margenes tanto en pantalla como en API. Puede leer antecedentes financieros sin contratar la gestión de tesorería, valores o gastos. Verificado de forma aislada y con contratos publicados.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['cobros'],
    complementos: [],
  },
  {
    id: 'A03',
    clave: 'reportes_comerciales',
    grupo: 'A',
    nombre: 'Análisis de productos y clientes',
    descripcion: 'Productos, mezcla de categorías y clientes',
    nota: 'Productos, mezcla y clientes verifican A03 y reportes.ver; los costos y márgenes se filtran según el permiso personal. Probado sin otros grupos de reportes ni módulos opcionales de gestión, conservando el aislamiento entre empresas.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes', 'clientes'],
    complementos: [],
  },
  {
    id: 'A04',
    clave: 'reportes_produccion',
    grupo: 'A',
    nombre: 'Análisis de capacidad y equipo',
    descripcion: 'Producción, equipo, alertas, umbrales y salud de ETA',
    nota: 'Lee historia sin exigir ETA, reparto o planificación avanzada. Umbrales revalida A04 bajo lock y exige reportes.ver y reportes.ver_resumen. Las alertas de rentabilidad requieren permiso de márgenes. API y rutas verificadas con A04 aislada, contratos publicados y cuenta vencida en consulta.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['tablero'],
    complementos: [],
  },
  {
    id: 'X01',
    clave: 'whatsapp_automatico',
    grupo: 'X',
    nombre: 'WhatsApp: avisos automáticos',
    descripcion:
      'WhatsApp oficial/WATI, plantillas, notificaciones, recordatorios y reseñas',
    nota: 'Encolado y autorización del envío coordinados con el contrato. Conserva historial y resolución auditada; los resultados inciertos no se reenvían automáticamente. Probado con versiones asignadas y cambios concurrentes; falta ampliar recorridos externos.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'X02',
    clave: 'whatsapp_web',
    grupo: 'X',
    nombre: 'WhatsApp Web y contexto comercial',
    descripcion:
      'Asistencia por WhatsApp Web, contexto de cliente y cola de automáticos',
    nota: 'Canal independiente: configuración, encolado, reserva e inicio coordinados con el contrato; conserva confirmaciones autorizadas, historial y resolución de inciertos. Probado con versiones asignadas y cambios concurrentes; falta recorrido con extensión real.',
    base: false,
    destino: 'plan',
    cobertura: 'implementada',
    revisionOperativa: false,
    requiere: ['clientes'],
    complementos: [],
  },
  {
    id: 'X03',
    clave: 'mcp',
    grupo: 'X',
    nombre: 'Cotización mediante MCP',
    descripcion: 'Herramientas de cotización por MCP y credenciales',
    nota: 'Creación y uso de credenciales exigen MCP en el contrato vigente, también con sesión cacheada. Humanos conservan listado y revocación; permisos e IP siguen vigentes.',
    base: false,
    destino: 'piloto',
    cobertura: 'implementada',
    revisionOperativa: true,
    requiere: ['cotizacion'],
    complementos: [],
  },
];

export type PreciosPlan = {
  moneda: 'USD';
  mensual: number | null;
  anual: number | null;
  usuarioMensual: number | null;
  usuarioAnual: number | null;
};
export const PRECIOS_PLAN_PENDIENTES: PreciosPlan = {
  moneda: 'USD',
  mensual: null,
  anual: null,
  usuarioMensual: null,
  usuarioAnual: null,
};

export type ContenidoPlan = {
  nombre: string;
  descripcion: string;
  usuariosIncluidos: number;
  adicionalesPermitidos: boolean;
  almacenamientoModo: 'pendiente' | 'limitado' | 'ilimitado';
  almacenamientoGb: number | null;
  funciones: Record<string, boolean>;
  /** Ausente en versiones anteriores; no implica un precio cero ni un plan gratuito. */
  precios?: PreciosPlan;
  comercial?: {
    acceso: 'publico' | 'invitacion';
    trialDias: number;
    implementacion: number;
  };
};
export type BorradorPlan = {
  id: string;
  codigo: string;
  orden: number;
  revision: number;
  catalogoVersion: number;
  actualizadoEl: string;
  contenido: ContenidoPlan;
};
export type CatalogoPlanesRespuesta = {
  catalogoVersion: number;
  capacidades: CapacidadPlan[];
  grupos: Record<string, string>;
  borradores: BorradorPlan[];
};
export const PROPUESTA_PLANES: {
  codigo: string;
  orden: number;
  contenido: ContenidoPlan;
}[] = [
  {
    codigo: 'esencial',
    orden: 0,
    contenido: {
      nombre: 'Grafo Esencial',
      descripcion: 'Cotizá, vendé y organizá tus trabajos.',
      usuariosIncluidos: 3,
      adicionalesPermitidos: true,
      almacenamientoModo: 'pendiente',
      almacenamientoGb: null,
      funciones: {
        identidad: true,
        roles: true,
        empresa: true,
        archivos: true,
        notificaciones: true,
        cuenta: true,
        cotizacion: true,
        presupuestos: true,
        aprobacion_presupuestos: true,
        documentos_pdf: true,
        ordenes: true,
        seguimiento_qr: true,
        proyectos: false,
        aprobacion_arte: false,
        clientes: true,
        cupones: false,
        fidelizacion: false,
        empleados: false,
        materiales: true,
        productos: true,
        productos_compuestos: true,
        procesos: true,
        centros_costo: true,
        maquinaria: true,
        reglas_precio: true,
        precios_especiales: false,
        analisis_vectorial: true,
        geometrias: true,
        aprovechamiento_cotizacion: true,
        nesting_irregular: false,
        exportacion_fabricacion: false,
        recorridos_fabricacion: false,
        centro_copiado: true,
        terminaciones_copiado: true,
        cotizacion_cad: true,
        impresion_directa: false,
        colas_impresion: false,
        etiquetas_pdf: true,
        tablero: true,
        estaciones: true,
        equipos_produccion: false,
        asignacion_automatica: false,
        eta_capacidad: false,
        planificacion_avanzada: false,
        colas_produccion: false,
        existencias: true,
        reservas: false,
        prevision_materiales: false,
        proveedores: true,
        compras: false,
        recepciones: false,
        cobros: true,
        cuentas_cobrar: true,
        tesoreria: false,
        valores: false,
        cuentas_pagar: false,
        gastos_recurrentes: false,
        gastos_fijos: true,
        fiscal_argentina: true,
        reportes_resumen: true,
        reportes_finanzas: false,
        reportes_comerciales: false,
        reportes_produccion: false,
        whatsapp_automatico: false,
        whatsapp_web: false,
        mcp: false,
      },
    },
  },
  {
    codigo: 'pro',
    orden: 1,
    contenido: {
      nombre: 'Grafo Pro',
      descripcion: 'Conectá ventas, materiales y administración.',
      usuariosIncluidos: 20,
      adicionalesPermitidos: true,
      almacenamientoModo: 'pendiente',
      almacenamientoGb: null,
      funciones: {
        identidad: true,
        roles: true,
        empresa: true,
        archivos: true,
        notificaciones: true,
        cuenta: true,
        cotizacion: true,
        presupuestos: true,
        aprobacion_presupuestos: true,
        documentos_pdf: true,
        ordenes: true,
        seguimiento_qr: true,
        proyectos: true,
        aprobacion_arte: true,
        clientes: true,
        cupones: true,
        fidelizacion: true,
        empleados: true,
        materiales: true,
        productos: true,
        productos_compuestos: true,
        procesos: true,
        centros_costo: true,
        maquinaria: true,
        reglas_precio: true,
        precios_especiales: true,
        analisis_vectorial: true,
        geometrias: true,
        aprovechamiento_cotizacion: true,
        nesting_irregular: true,
        exportacion_fabricacion: false,
        recorridos_fabricacion: false,
        centro_copiado: true,
        terminaciones_copiado: true,
        cotizacion_cad: true,
        impresion_directa: false,
        colas_impresion: false,
        etiquetas_pdf: true,
        tablero: true,
        estaciones: true,
        equipos_produccion: true,
        asignacion_automatica: false,
        eta_capacidad: false,
        planificacion_avanzada: false,
        colas_produccion: false,
        existencias: true,
        reservas: true,
        prevision_materiales: true,
        proveedores: true,
        compras: true,
        recepciones: true,
        cobros: true,
        cuentas_cobrar: true,
        tesoreria: true,
        valores: true,
        cuentas_pagar: true,
        gastos_recurrentes: true,
        gastos_fijos: true,
        fiscal_argentina: true,
        reportes_resumen: true,
        reportes_finanzas: true,
        reportes_comerciales: true,
        reportes_produccion: false,
        whatsapp_automatico: true,
        whatsapp_web: true,
        mcp: false,
      },
    },
  },
  {
    codigo: 'avanzado',
    orden: 2,
    contenido: {
      nombre: 'Grafo Avanzado',
      descripcion: 'Planificá y optimizá toda tu producción.',
      usuariosIncluidos: 40,
      adicionalesPermitidos: true,
      almacenamientoModo: 'pendiente',
      almacenamientoGb: null,
      funciones: {
        identidad: true,
        roles: true,
        empresa: true,
        archivos: true,
        notificaciones: true,
        cuenta: true,
        cotizacion: true,
        presupuestos: true,
        aprobacion_presupuestos: true,
        documentos_pdf: true,
        ordenes: true,
        seguimiento_qr: true,
        proyectos: true,
        aprobacion_arte: true,
        clientes: true,
        cupones: true,
        fidelizacion: true,
        empleados: true,
        materiales: true,
        productos: true,
        productos_compuestos: true,
        procesos: true,
        centros_costo: true,
        maquinaria: true,
        reglas_precio: true,
        precios_especiales: true,
        analisis_vectorial: true,
        geometrias: true,
        aprovechamiento_cotizacion: true,
        nesting_irregular: true,
        exportacion_fabricacion: false,
        recorridos_fabricacion: false,
        centro_copiado: true,
        terminaciones_copiado: true,
        cotizacion_cad: true,
        impresion_directa: false,
        colas_impresion: false,
        etiquetas_pdf: true,
        tablero: true,
        estaciones: true,
        equipos_produccion: true,
        asignacion_automatica: true,
        eta_capacidad: true,
        planificacion_avanzada: true,
        colas_produccion: true,
        existencias: true,
        reservas: true,
        prevision_materiales: true,
        proveedores: true,
        compras: true,
        recepciones: true,
        cobros: true,
        cuentas_cobrar: true,
        tesoreria: true,
        valores: true,
        cuentas_pagar: true,
        gastos_recurrentes: true,
        gastos_fijos: true,
        fiscal_argentina: true,
        reportes_resumen: true,
        reportes_finanzas: true,
        reportes_comerciales: true,
        reportes_produccion: true,
        whatsapp_automatico: true,
        whatsapp_web: true,
        mcp: false,
      },
    },
  },
];
