/** Catálogo comercial propuesto. No sustituye los derechos efectivos de las suscripciones. */
export const VERSION_CATALOGO_PLANES = 1;
export type CapacidadPlan = {
  id: string;
  clave: string;
  grupo: string;
  nombre: string;
  descripcion: string;
  nota: string;
  base: boolean;
  destino: 'plan' | 'piloto' | 'adicional';
  cobertura: 'base' | 'parcial' | 'pendiente';
  revisionOperativa: boolean;
  requiere: string[];
  complementos: string[];
};
export const GRUPOS_PLANES: Record<string, string> = {
  B: 'Cuenta y seguridad',
  C: 'Venta y órdenes',
  R: 'Clientes y equipo',
  T: 'Catálogo y costos',
  G: 'Geometría y fabricación',
  I: 'Copiado e impresión',
  P: 'Producción y planificación',
  S: 'Stock y compras',
  F: 'Administración',
  A: 'Reportes',
  X: 'Integraciones',
};

export const CATALOGO_PLANES: CapacidadPlan[] = [
  {
    id: 'B01',
    clave: 'identidad',
    grupo: 'B',
    nombre: 'Identidad, perfil y MFA',
    descripcion:
      'Identidad, login, contraseña, perfil, foto, MFA, recuperación y sesiones',
    nota: 'Base técnica; seguridad disponible en todos los planes',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B02',
    clave: 'roles',
    grupo: 'B',
    nombre: 'Usuarios, roles y permisos',
    descripcion:
      'Aislamiento de empresa, pertenencias, roles, permisos y restricciones de acceso',
    nota: 'Base técnica; el plan nunca concede un permiso personal',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B03',
    clave: 'empresa',
    grupo: 'B',
    nombre: 'Empresa y marca',
    descripcion: 'Datos y marca de la empresa, país y configuración general',
    nota: 'Base técnica; requisitos fiscales y regionales separados de la oferta',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B04',
    clave: 'archivos',
    grupo: 'B',
    nombre: 'Archivos y versiones',
    descripcion: 'Archivos, versiones, descarga, papelera y restauración',
    nota: 'Base compartida con cupo independiente; política de conservación explícita',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B05',
    clave: 'notificaciones',
    grupo: 'B',
    nombre: 'Notificaciones internas',
    descripcion: 'Notificaciones internas, eventos y resumen de actividad',
    nota: 'Base compartida; no confundir con mensajería externa paga',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'B06',
    clave: 'cuenta',
    grupo: 'B',
    nombre: 'Cuenta y suscripción',
    descripcion:
      'Alta, suscripción, medios de gestión del cobro SaaS y acceso a soporte',
    nota: 'Base técnica; Backoffice y Paddle son operación de Grafo',
    base: true,
    destino: 'plan',
    cobertura: 'base',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'C01',
    clave: 'cotizacion',
    grupo: 'C',
    nombre: 'Cotizador completo',
    descripcion: 'Cotización, varios ítems, cálculo y recotización',
    nota: 'Catálogo y costos T01–T05. Stock S03 puede enriquecer la fecha, sin impedir cotizar por falta de material',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [
      'materiales',
      'productos',
      'procesos',
      'centros_costo',
      'reglas_precio',
    ],
    complementos: ['prevision_materiales'],
  },
  {
    id: 'C02',
    clave: 'presupuestos',
    grupo: 'C',
    nombre: 'Presupuestos',
    descripcion: 'Presupuestos, emisión, respuesta comercial y conversión a OT',
    nota: 'C01; separar la gestión del presupuesto de sus canales de envío',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['cotizacion', 'clientes'],
    complementos: [],
  },
  {
    id: 'C03',
    clave: 'aprobacion_presupuestos',
    grupo: 'C',
    nombre: 'Aprobación pública de presupuestos',
    descripcion: 'Presupuesto público y aprobación del cliente',
    nota: 'C02; conservar la trazabilidad y definir continuidad de enlaces al cambiar de plan',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['presupuestos'],
    complementos: [],
  },
  {
    id: 'C04',
    clave: 'documentos_pdf',
    grupo: 'C',
    nombre: 'Documentos PDF',
    descripcion: 'Documentos PDF del negocio',
    nota: 'Recurso transversal a presupuesto, OT, recibo y factura. La tecnología del generador no es una prestación comercial',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'C05',
    clave: 'ordenes',
    grupo: 'C',
    nombre: 'Órdenes y entrega',
    descripcion:
      'Órdenes, ítems, emisión, modificaciones, cancelación y entrega',
    nota: 'C01; puede operar con cobro básico F01 y sin impresión directa',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['cotizacion', 'clientes'],
    complementos: [],
  },
  {
    id: 'C06',
    clave: 'seguimiento_qr',
    grupo: 'C',
    nombre: 'Seguimiento y QR',
    descripcion: 'Seguimiento público, identificación QR y entrega por escaneo',
    nota: 'C05; distinguir QR interno de entrega y enlace público de seguimiento',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'C07',
    clave: 'proyectos',
    grupo: 'C',
    nombre: 'Campañas y proyectos',
    descripcion:
      'Campañas/proyectos: equipo, hitos y agrupación de presupuestos y OT',
    nota: 'Control en rutas de campañas y vinculación al crear presupuestos/OT; navegación y selector condicionados. Pendiente política de continuidad de campañas abiertas.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['presupuestos', 'ordenes'],
    complementos: [],
  },
  {
    id: 'C08',
    clave: 'aprobacion_arte',
    grupo: 'C',
    nombre: 'Aprobación de arte y revisiones',
    descripcion:
      'Desarrollo documental, revisiones de arte, solicitudes, aprobación y liberación',
    nota: 'Control en acciones internas de arte y materialización automática de requisitos. Los gates y enlaces históricos se conservan; falta completar la política de cambio de plan.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['ordenes', 'archivos'],
    complementos: [],
  },
  {
    id: 'R01',
    clave: 'clientes',
    grupo: 'R',
    nombre: 'Clientes y contactos',
    descripcion: 'Clientes, contactos, importación y consulta de su actividad',
    nota: 'Registro compartido por ventas y administración',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'R02',
    clave: 'cupones',
    grupo: 'R',
    nombre: 'Cupones',
    descripcion: 'Cupones, validación y uso',
    nota: 'Control en rutas, validación, reserva y redención; el cotizador omite selector y lector sin capacidad. Pendiente política de cupones ya comprometidos al cambiar de plan.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['cotizacion'],
    complementos: [],
  },
  {
    id: 'R03',
    clave: 'fidelizacion',
    grupo: 'R',
    nombre: 'Fidelización',
    descripcion: 'Fidelización, configuración, ajustes y simulación',
    nota: 'Control en rutas, canjes y acumulación automática al emitir/cobrar/entregar; sin capacidad no genera puntos ni cuentas. Se conservan reversos históricos. Pendiente transición comercial de canjes abiertos.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['clientes'],
    complementos: [],
  },
  {
    id: 'R04',
    clave: 'empleados',
    grupo: 'R',
    nombre: 'Registro de empleados',
    descripcion:
      'Empleados, vinculación a usuarios, capacidades y remuneraciones',
    nota: 'Registro de personal/costos; no implica un sistema completo de liquidación de sueldos',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T01',
    clave: 'materiales',
    grupo: 'T',
    nombre: 'Materiales, variantes y costos',
    descripcion:
      'Materiales, variantes, unidades, presentaciones, costos y biblioteca',
    nota: 'Base del cálculo; independiente de contratar gestión operativa de stock',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T02',
    clave: 'productos',
    grupo: 'T',
    nombre: 'Productos y formularios',
    descripcion: 'Productos, formularios y configuración comercial',
    nota: 'Usa materiales y procesos; conservar lectura de productos históricos',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'T03',
    clave: 'productos_compuestos',
    grupo: 'T',
    nombre: 'Productos compuestos y recetas',
    descripcion: 'Recetas, componentes, revisiones y publicación del producto',
    nota: 'T02; evaluar la composición avanzada como paquete, sin romper componentes ya utilizados',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['productos'],
    complementos: [],
  },
  {
    id: 'T04',
    clave: 'procesos',
    grupo: 'T',
    nombre: 'Procesos y flujos',
    descripcion:
      'Procesos reutilizables, familias, flujos y alternativas de producción',
    nota: 'Compartido entre cotización y ejecución; una familia técnica no equivale automáticamente a un adicional comercial',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'T05',
    clave: 'centros_costo',
    grupo: 'T',
    nombre: 'Centros de costo y tarifas',
    descripcion: 'Centros de costo, tarifas, capacidades e historial',
    nota: 'Base de costos y planificación; separar mantenimiento del costo de herramientas avanzadas de planificación',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T06',
    clave: 'maquinaria',
    grupo: 'T',
    nombre: 'Maquinaria y consumos',
    descripcion: 'Maquinaria, perfiles, consumos e historial',
    nota: 'T05; maquinaria productiva e impresora conectada I04 son conceptos diferentes',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['centros_costo'],
    complementos: [],
  },
  {
    id: 'T07',
    clave: 'reglas_precio',
    grupo: 'T',
    nombre: 'Precios, impuestos y monedas',
    descripcion:
      'Cargos, impuestos, comisiones, reglas de precio y tipos de cambio',
    nota: 'Recurso común del cálculo; configuración regional independiente de ARCA',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'T08',
    clave: 'precios_especiales',
    grupo: 'T',
    nombre: 'Precios especiales por cliente',
    descripcion: 'Precios especiales por cliente/producto',
    nota: 'R01/T02; posible agrupación comercial avanzada',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['clientes', 'productos'],
    complementos: [],
  },
  {
    id: 'G01',
    clave: 'analisis_vectorial',
    grupo: 'G',
    nombre: 'Medición y análisis vectorial',
    descripcion: 'Análisis y preparación vectorial, medidas y geometrías',
    nota: 'Puede alimentar C01; no apagar primitivas compartidas al retirar una herramienta avanzada',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'G02',
    clave: 'geometrias',
    grupo: 'G',
    nombre: 'Geometrías del producto',
    descripcion: 'Geometrías del producto e interpretación por lotes',
    nota: 'T02/G01; diferenciar mantenimiento de geometrías de exportación fabril',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['analisis_vectorial', 'productos'],
    complementos: [],
  },
  {
    id: 'G03',
    clave: 'aprovechamiento_cotizacion',
    grupo: 'G',
    nombre: 'Aprovechamiento para cotizar',
    descripcion:
      'Nesting y preparaciones guardadas para aprovechamiento del material',
    nota: 'G01/T01; revisar consumo desde cotización y colas de producción',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['analisis_vectorial', 'materiales'],
    complementos: [],
  },
  {
    id: 'G04',
    clave: 'exportacion_fabricacion',
    grupo: 'G',
    nombre: 'Exportación de fabricación DXF',
    descripcion: 'Exportación de fabricación y capas DXF',
    nota: 'G02; candidata a herramienta avanzada, con permisos y formatos explícitos',
    base: false,
    destino: 'adicional',
    cobertura: 'pendiente',
    revisionOperativa: true,
    requiere: ['geometrias'],
    complementos: [],
  },
  {
    id: 'G05',
    clave: 'recorridos_fabricacion',
    grupo: 'G',
    nombre: 'Recorridos y plantillas de fabricación',
    descripcion: 'Recorridos, revisiones y archivos de fabricación/plantillas',
    nota: 'La emisión no prepara recorridos automáticamente sin capacidad. Pendiente completar todos los endpoints de fabricación y el tratamiento de trabajos históricos.',
    base: false,
    destino: 'adicional',
    cobertura: 'parcial',
    revisionOperativa: true,
    requiere: ['geometrias'],
    complementos: [],
  },
  {
    id: 'I01',
    clave: 'centro_copiado',
    grupo: 'I',
    nombre: 'Centro de copiado: documentos',
    descripcion:
      'Cotización de documentos: PDF, páginas/rangos, copias, orientación, color, faz y papel',
    nota: '`centroCopiado`; puede funcionar sin envío a impresora',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['cotizacion', 'archivos'],
    complementos: [],
  },
  {
    id: 'I02',
    clave: 'terminaciones_copiado',
    grupo: 'I',
    nombre: 'Terminaciones y tomos',
    descripcion: 'Terminaciones, agrupación y tomos',
    nota: 'Comparte `centroCopiado`; no tiene interruptor comercial propio',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['centro_copiado'],
    complementos: [],
  },
  {
    id: 'I03',
    clave: 'cotizacion_cad',
    grupo: 'I',
    nombre: 'Cotización de planos CAD',
    descripcion:
      'Cotización CAD por rollo, tamaños grandes y configuración por página',
    nota: 'Comparte `centroCopiado` con documentos. Separarlos comercialmente exige nuevos controles',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['centro_copiado', 'materiales'],
    complementos: [],
  },
  {
    id: 'I04',
    clave: 'impresion_directa',
    grupo: 'I',
    nombre: 'Impresión conectada',
    descripcion:
      'Impresión directa: conexión QZ, impresoras, bandejas y perfiles',
    nota: '`impresionDirecta` explícito; hoy agrupa láser, CAD y térmica',
    base: false,
    destino: 'piloto',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: [],
    complementos: [],
  },
  {
    id: 'I05',
    clave: 'colas_impresion',
    grupo: 'I',
    nombre: 'Asistente y colas de impresión',
    descripcion:
      'Asistente, colas por máquina, preparación del operario, envíos y confirmaciones',
    nota: 'I04; distinguir estado de cola y validación física',
    base: false,
    destino: 'piloto',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['impresion_directa'],
    complementos: [],
  },
  {
    id: 'I06',
    clave: 'etiquetas_pdf',
    grupo: 'I',
    nombre: 'Etiquetas descargables',
    descripcion: 'Etiquetas QR y descarga para impresión manual',
    nota: 'C05/C06; la vía manual está exceptuada mediante `ImpresionManual`',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'P01',
    clave: 'tablero',
    grupo: 'P',
    nombre: 'Tablero y tareas',
    descripcion: 'Tablero, lista, tareas, tramos y progreso del trabajo',
    nota: 'C05/T04; base de ejecución',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['ordenes', 'procesos'],
    complementos: [],
  },
  {
    id: 'P02',
    clave: 'estaciones',
    grupo: 'P',
    nombre: 'Estaciones y calendarios',
    descripcion: 'Estaciones, recursos, calendarios y disponibilidad',
    nota: 'T05/T06; insumo para planificación, además de configuración operativa',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['centros_costo'],
    complementos: [],
  },
  {
    id: 'P03',
    clave: 'equipos_produccion',
    grupo: 'P',
    nombre: 'Equipos productivos',
    descripcion: 'Equipos productivos y capacidades',
    nota: 'R04/P02; empleados sin login no equivalen automáticamente a usuarios de licencia',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['empleados', 'estaciones'],
    complementos: [],
  },
  {
    id: 'P04',
    clave: 'asignacion_automatica',
    grupo: 'P',
    nombre: 'Asignación automática de personal',
    descripcion:
      'Asignación de personal: simulación, confirmación y reconciliación',
    nota: 'El servicio de asignación verifica la capacidad también cuando lo invoca el scheduler. La producción manual continúa; pendiente continuidad de asignaciones previas al cambiar de plan.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['tablero', 'equipos_produccion'],
    complementos: [],
  },
  {
    id: 'P05',
    clave: 'eta_capacidad',
    grupo: 'P',
    nombre: 'Estimación según capacidad',
    descripcion: 'ETA, contexto y estimaciones de capacidad/entrega',
    nota: 'Control en API, contexto de simulación, promesas, cierres y snapshots automáticos. Cotizador y tablero operan con fecha manual sin ETA. Quedan por revisar todas las lecturas analíticas históricas.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['tablero', 'estaciones'],
    complementos: ['prevision_materiales'],
  },
  {
    id: 'P06',
    clave: 'planificacion_avanzada',
    grupo: 'P',
    nombre: 'Escenarios y reprogramación',
    descripcion: 'Escenarios de planificación, elección y reprogramación',
    nota: 'Control en rutas, solicitudes, selección, reprogramación, worker y materialización de entregas en OT. Pendiente política de continuidad de planes y lotes abiertos.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['eta_capacidad'],
    complementos: [],
  },
  {
    id: 'P07',
    clave: 'colas_produccion',
    grupo: 'P',
    nombre: 'Optimización de colas productivas',
    descripcion: 'Colas productivas, agrupación y acciones sobre trabajos',
    nota: 'Rutas y navegación protegidas por capacidad; pendiente barrido de servicios internos, lotes abiertos y cambios de plan.',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['tablero'],
    complementos: [],
  },
  {
    id: 'S01',
    clave: 'existencias',
    grupo: 'S',
    nombre: 'Existencias y movimientos',
    descripcion:
      'Almacenes, ubicaciones, existencias, transferencias y movimientos',
    nota: 'T01; catálogo de materiales y existencias son niveles diferentes',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'S02',
    clave: 'reservas',
    grupo: 'S',
    nombre: 'Reservas automáticas por OT',
    descripcion: 'Reservas de materiales por OT y consumo',
    nota: 'Servicio conectado al evaluador: emisión, comandos y política. Probado sin reservas en Esencial; faltan asignación real y continuidad de cambios de plan',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: true,
    requiere: ['existencias', 'ordenes'],
    complementos: [],
  },
  {
    id: 'S03',
    clave: 'prevision_materiales',
    grupo: 'S',
    nombre: 'Previsión de faltantes',
    descripcion: 'Previsión de materiales durante cotización',
    nota: 'El evaluador permite omitir previsión sin condicionar la cotización. Faltan asignación real y validación completa del recorrido comercial',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: true,
    requiere: ['existencias', 'cotizacion'],
    complementos: [],
  },
  {
    id: 'S04',
    clave: 'proveedores',
    grupo: 'S',
    nombre: 'Proveedores y reposición',
    descripcion: 'Proveedores, ofertas/costos y plazos de reposición',
    nota: 'T01; registro de proveedor reutilizable en egresos y compras',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['materiales'],
    complementos: [],
  },
  {
    id: 'S05',
    clave: 'compras',
    grupo: 'S',
    nombre: 'Compras y abastecimiento',
    descripcion:
      'Necesidades de abastecimiento, borradores y pedidos de compra',
    nota: 'S04/T01; conectar S02 cuando una necesidad proviene de una OT',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: true,
    requiere: ['proveedores'],
    complementos: [],
  },
  {
    id: 'S06',
    clave: 'recepciones',
    grupo: 'S',
    nombre: 'Recepciones de materiales',
    descripcion:
      'Recepciones y actualización de stock, incluidas recepciones parciales',
    nota: 'S05/S01; conservar trazabilidad de operaciones iniciadas ante cambios de plan',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: true,
    requiere: ['existencias', 'compras'],
    complementos: [],
  },
  {
    id: 'F01',
    clave: 'cobros',
    grupo: 'F',
    nombre: 'Cobros, señas y recibos',
    descripcion: 'Cobros, señas, imputaciones, métodos de pago y recibos',
    nota: 'C05/R01; definir un cobro básico compatible con entregar una OT, sin exigir tesorería avanzada',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['clientes'],
    complementos: [],
  },
  {
    id: 'F02',
    clave: 'cuentas_cobrar',
    grupo: 'F',
    nombre: 'Saldos y cuentas por cobrar',
    descripcion: 'Cuentas por cobrar, deudores y estado de cuenta',
    nota: 'F01/R01; independiente de emitir fiscalmente con ARCA',
    base: false,
    destino: 'plan',
    cobertura: 'pendiente',
    revisionOperativa: false,
    requiere: ['cobros'],
    complementos: [],
  },
  {
    id: 'F03',
    clave: 'tesoreria',
    grupo: 'F',
    nombre: 'Tesorería y conciliación',
    descripcion:
      'Tesorería, cuentas, movimientos, transferencias, arqueos y conciliación',
    nota: 'F01; posible agrupación avanzada',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['cobros'],
    complementos: [],
  },
  {
    id: 'F04',
    clave: 'valores',
    grupo: 'F',
    nombre: 'Valores y cheques',
    descripcion:
      'Valores y cheques: depósito, acreditación, rechazo y reversión',
    nota: 'F03; contemplar acreditaciones programadas',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['tesoreria'],
    complementos: [],
  },
  {
    id: 'F05',
    clave: 'cuentas_pagar',
    grupo: 'F',
    nombre: 'Egresos y cuentas por pagar',
    descripcion: 'Egresos, cuentas por pagar y órdenes de pago',
    nota: 'S04/F03 según operación; compra y pago son dominios distintos',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['proveedores'],
    complementos: [],
  },
  {
    id: 'F06',
    clave: 'gastos_recurrentes',
    grupo: 'F',
    nombre: 'Gastos recurrentes',
    descripcion: 'Gastos recurrentes y generación programada',
    nota: 'F05; comprobar tanto alta como ejecución del scheduler',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['cuentas_pagar'],
    complementos: [],
  },
  {
    id: 'F07',
    clave: 'gastos_fijos',
    grupo: 'F',
    nombre: 'Gastos fijos y costos',
    descripcion: 'Gastos fijos y estructura de costos',
    nota: 'T05/R04; no retirar los insumos necesarios del cálculo básico por una decisión de packaging',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['centros_costo'],
    complementos: [],
  },
  {
    id: 'F08',
    clave: 'fiscal_argentina',
    grupo: 'F',
    nombre: 'Comprobantes y ARCA (Argentina)',
    descripcion: 'Comprobantes, notas y facturación electrónica argentina',
    nota: 'Existe `afip` para integración/emisión fiscal. Separar comprobantes manuales, gestión financiera y servicio fiscal; país/configuración también aplican',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'A01',
    clave: 'reportes_resumen',
    grupo: 'A',
    nombre: 'Resumen comercial y operativo',
    descripcion: 'Resumen, evolución comercial y embudo',
    nota: 'C02/C05; separar resumen operativo de análisis avanzado',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'A02',
    clave: 'reportes_finanzas',
    grupo: 'A',
    nombre: 'Análisis financiero y márgenes',
    descripcion: 'Análisis financiero y márgenes',
    nota: 'F01–F07; los permisos para ver márgenes siguen aplicando aun con la función contratada',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['cobros'],
    complementos: [],
  },
  {
    id: 'A03',
    clave: 'reportes_comerciales',
    grupo: 'A',
    nombre: 'Análisis de productos y clientes',
    descripcion: 'Productos, mezcla de categorías y clientes',
    nota: 'R01/T02/C05; validar experiencia con módulos opcionales ausentes',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['ordenes', 'clientes'],
    complementos: [],
  },
  {
    id: 'A04',
    clave: 'reportes_produccion',
    grupo: 'A',
    nombre: 'Análisis de capacidad y equipo',
    descripcion: 'Producción, equipo, alertas, umbrales y salud de ETA',
    nota: 'P01–P06 según informe; no hacer depender todos los reportes de planificación avanzada',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['tablero'],
    complementos: [],
  },
  {
    id: 'X01',
    clave: 'whatsapp_automatico',
    grupo: 'X',
    nombre: 'WhatsApp: avisos automáticos',
    descripcion:
      'WhatsApp oficial/WATI, plantillas, notificaciones, recordatorios y reseñas',
    nota: 'Validado al encolar, despachar y ejecutar tareas de WATI. La continuidad al cambiar de plan se resuelve antes de publicar',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['ordenes'],
    complementos: [],
  },
  {
    id: 'X02',
    clave: 'whatsapp_web',
    grupo: 'X',
    nombre: 'WhatsApp Web y contexto comercial',
    descripcion:
      'Asistencia por WhatsApp Web, contexto de cliente y cola de automáticos',
    nota: 'Canal independiente: control en contexto, configuración, reserva e inicio de envío de la extensión; conserva confirmaciones de envíos ya autorizados',
    base: false,
    destino: 'plan',
    cobertura: 'parcial',
    revisionOperativa: false,
    requiere: ['clientes'],
    complementos: [],
  },
  {
    id: 'X03',
    clave: 'mcp',
    grupo: 'X',
    nombre: 'Cotización mediante MCP',
    descripcion: 'Herramientas de cotización por MCP y credenciales',
    nota: 'C01 y permisos del actor. El catálogo debe evaluar también este acceso; no equivale a ofrecer una API pública general de todo el ERP',
    base: false,
    destino: 'piloto',
    cobertura: 'pendiente',
    revisionOperativa: true,
    requiere: ['cotizacion'],
    complementos: [],
  },
];

export type ContenidoPlan = {
  nombre: string;
  descripcion: string;
  usuariosIncluidos: number;
  adicionalesPermitidos: boolean;
  almacenamientoModo: 'pendiente' | 'limitado' | 'ilimitado';
  almacenamientoGb: number | null;
  funciones: Record<string, boolean>;
};
export type BorradorPlan = {
  id: string;
  codigo: string;
  orden: number;
  revision: number;
  catalogoVersion: number;
  actualizadoEl: string;
  contenido: ContenidoPlan;
};
export type CatalogoPlanesRespuesta = {
  catalogoVersion: number;
  capacidades: CapacidadPlan[];
  grupos: Record<string, string>;
  borradores: BorradorPlan[];
};
export const PROPUESTA_PLANES: {
  codigo: string;
  orden: number;
  contenido: ContenidoPlan;
}[] = [
  {
    codigo: 'esencial',
    orden: 0,
    contenido: {
      nombre: 'Grafo Esencial',
      descripcion: 'Cotizá, vendé y organizá tus trabajos.',
      usuariosIncluidos: 3,
      adicionalesPermitidos: true,
      almacenamientoModo: 'pendiente',
      almacenamientoGb: null,
      funciones: {
        identidad: true,
        roles: true,
        empresa: true,
        archivos: true,
        notificaciones: true,
        cuenta: true,
        cotizacion: true,
        presupuestos: true,
        aprobacion_presupuestos: true,
        documentos_pdf: true,
        ordenes: true,
        seguimiento_qr: true,
        proyectos: false,
        aprobacion_arte: false,
        clientes: true,
        cupones: false,
        fidelizacion: false,
        empleados: false,
        materiales: true,
        productos: true,
        productos_compuestos: true,
        procesos: true,
        centros_costo: true,
        maquinaria: true,
        reglas_precio: true,
        precios_especiales: false,
        analisis_vectorial: true,
        geometrias: true,
        aprovechamiento_cotizacion: true,
        exportacion_fabricacion: false,
        recorridos_fabricacion: false,
        centro_copiado: true,
        terminaciones_copiado: true,
        cotizacion_cad: true,
        impresion_directa: false,
        colas_impresion: false,
        etiquetas_pdf: true,
        tablero: true,
        estaciones: true,
        equipos_produccion: false,
        asignacion_automatica: false,
        eta_capacidad: false,
        planificacion_avanzada: false,
        colas_produccion: false,
        existencias: true,
        reservas: false,
        prevision_materiales: false,
        proveedores: true,
        compras: false,
        recepciones: false,
        cobros: true,
        cuentas_cobrar: true,
        tesoreria: false,
        valores: false,
        cuentas_pagar: false,
        gastos_recurrentes: false,
        gastos_fijos: true,
        fiscal_argentina: true,
        reportes_resumen: true,
        reportes_finanzas: false,
        reportes_comerciales: false,
        reportes_produccion: false,
        whatsapp_automatico: false,
        whatsapp_web: false,
        mcp: false,
      },
    },
  },
  {
    codigo: 'pro',
    orden: 1,
    contenido: {
      nombre: 'Grafo Pro',
      descripcion: 'Conectá ventas, materiales y administración.',
      usuariosIncluidos: 20,
      adicionalesPermitidos: true,
      almacenamientoModo: 'pendiente',
      almacenamientoGb: null,
      funciones: {
        identidad: true,
        roles: true,
        empresa: true,
        archivos: true,
        notificaciones: true,
        cuenta: true,
        cotizacion: true,
        presupuestos: true,
        aprobacion_presupuestos: true,
        documentos_pdf: true,
        ordenes: true,
        seguimiento_qr: true,
        proyectos: true,
        aprobacion_arte: true,
        clientes: true,
        cupones: true,
        fidelizacion: true,
        empleados: true,
        materiales: true,
        productos: true,
        productos_compuestos: true,
        procesos: true,
        centros_costo: true,
        maquinaria: true,
        reglas_precio: true,
        precios_especiales: true,
        analisis_vectorial: true,
        geometrias: true,
        aprovechamiento_cotizacion: true,
        exportacion_fabricacion: false,
        recorridos_fabricacion: false,
        centro_copiado: true,
        terminaciones_copiado: true,
        cotizacion_cad: true,
        impresion_directa: false,
        colas_impresion: false,
        etiquetas_pdf: true,
        tablero: true,
        estaciones: true,
        equipos_produccion: true,
        asignacion_automatica: false,
        eta_capacidad: false,
        planificacion_avanzada: false,
        colas_produccion: false,
        existencias: true,
        reservas: true,
        prevision_materiales: true,
        proveedores: true,
        compras: true,
        recepciones: true,
        cobros: true,
        cuentas_cobrar: true,
        tesoreria: true,
        valores: true,
        cuentas_pagar: true,
        gastos_recurrentes: true,
        gastos_fijos: true,
        fiscal_argentina: true,
        reportes_resumen: true,
        reportes_finanzas: true,
        reportes_comerciales: true,
        reportes_produccion: false,
        whatsapp_automatico: true,
        whatsapp_web: true,
        mcp: false,
      },
    },
  },
  {
    codigo: 'avanzado',
    orden: 2,
    contenido: {
      nombre: 'Grafo Avanzado',
      descripcion: 'Planificá y optimizá toda tu producción.',
      usuariosIncluidos: 40,
      adicionalesPermitidos: true,
      almacenamientoModo: 'pendiente',
      almacenamientoGb: null,
      funciones: {
        identidad: true,
        roles: true,
        empresa: true,
        archivos: true,
        notificaciones: true,
        cuenta: true,
        cotizacion: true,
        presupuestos: true,
        aprobacion_presupuestos: true,
        documentos_pdf: true,
        ordenes: true,
        seguimiento_qr: true,
        proyectos: true,
        aprobacion_arte: true,
        clientes: true,
        cupones: true,
        fidelizacion: true,
        empleados: true,
        materiales: true,
        productos: true,
        productos_compuestos: true,
        procesos: true,
        centros_costo: true,
        maquinaria: true,
        reglas_precio: true,
        precios_especiales: true,
        analisis_vectorial: true,
        geometrias: true,
        aprovechamiento_cotizacion: true,
        exportacion_fabricacion: false,
        recorridos_fabricacion: false,
        centro_copiado: true,
        terminaciones_copiado: true,
        cotizacion_cad: true,
        impresion_directa: false,
        colas_impresion: false,
        etiquetas_pdf: true,
        tablero: true,
        estaciones: true,
        equipos_produccion: true,
        asignacion_automatica: true,
        eta_capacidad: true,
        planificacion_avanzada: true,
        colas_produccion: true,
        existencias: true,
        reservas: true,
        prevision_materiales: true,
        proveedores: true,
        compras: true,
        recepciones: true,
        cobros: true,
        cuentas_cobrar: true,
        tesoreria: true,
        valores: true,
        cuentas_pagar: true,
        gastos_recurrentes: true,
        gastos_fijos: true,
        fiscal_argentina: true,
        reportes_resumen: true,
        reportes_finanzas: true,
        reportes_comerciales: true,
        reportes_produccion: true,
        whatsapp_automatico: true,
        whatsapp_web: true,
        mcp: false,
      },
    },
  },
];
